/* ---------- TikTok comprehensive data store ---------- */

export const TIKTOK_DATA: Record<string, any> = {
  /* -----------------------------------------------------------
   * 1. Categories
   * --------------------------------------------------------- */
  'tiktok.categories': {
    items: [
      { id: 'cat-foryou', name: 'For You', icon: 'Sparkles' },
      { id: 'cat-following', name: 'Following', icon: 'UserGroup' },
      { id: 'cat-live', name: 'Live', icon: 'Broadcast' },
      { id: 'cat-gaming', name: 'Gaming', icon: 'Controller' },
      { id: 'cat-comedy', name: 'Comedy', icon: 'Smile' },
      { id: 'cat-cooking', name: 'Cooking', icon: 'ChefHat' },
      { id: 'cat-dance', name: 'Dance', icon: 'Music' },
      { id: 'cat-sports', name: 'Sports', icon: 'Trophy' },
      { id: 'cat-music', name: 'Music', icon: 'Note' },
      { id: 'cat-diy', name: 'DIY', icon: 'Hammer' },
    ],
  },

  /* -----------------------------------------------------------
   * 2. Feed videos
   * --------------------------------------------------------- */
  'tiktok.feed.videos': {
    items: [
      {
        id: 'vid-feed-01',
        creator: 'Maya Chen',
        handle: '@mayachen.cooks',
        avatar: 'MC',
        caption: '15-minute spicy ramen hack that broke the internet 🍜🔥 #ramen #noodlehack',
        sound: 'original sound - mayachen.cooks',
        likes: '1.2M',
        comments: '8.4K',
        shares: '42K',
        duration: 58,
      },
      {
        id: 'vid-feed-02',
        creator: 'Devon Parker',
        handle: '@devonpark',
        avatar: 'DP',
        caption: 'POV: you finally landed the kickflip after 200 tries 🛹 #skateboarding #kickflip',
        sound: 'Lo-fi Hip Hop Beats - chillhop',
        likes: '487K',
        comments: '3.1K',
        shares: '12K',
        duration: 24,
      },
      {
        id: 'vid-feed-03',
        creator: 'Aisha Bello',
        handle: '@aishabello',
        avatar: 'AB',
        caption: 'This makeup transition took 6 hours to film 💄✨ #makeup #transition',
        sound: 'Sapphire - Beyoncé',
        likes: '2.4M',
        comments: '15.2K',
        shares: '88K',
        duration: 12,
      },
      {
        id: 'vid-feed-04',
        creator: 'Leo Martinez',
        handle: '@leomtz',
        avatar: 'LM',
        caption: 'Teaching my golden retriever to skateboard was a mistake 🐶🛹 #dogsoftiktok',
        sound: 'Funny Dog Beat - viral audio',
        likes: '3.1M',
        comments: '24K',
        shares: '120K',
        duration: 30,
      },
      {
        id: 'vid-feed-05',
        creator: 'Sofia Rossi',
        handle: '@sofiarossi',
        avatar: 'SR',
        caption: 'Sunset over Amalfi coast never gets old 🌅🇮🇹 #travel #italy #sunset',
        sound: 'La Vie En Rose - Louis Armstrong',
        likes: '892K',
        comments: '5.6K',
        shares: '34K',
        duration: 18,
      },
      {
        id: 'vid-feed-06',
        creator: 'Marcus Webb',
        handle: '@marcuswebb',
        avatar: 'MW',
        caption: 'I built a gaming PC for $200 and it actually works 🎮💰 #pcbuild #budgetgaming',
        sound: 'original sound - marcuswebb',
        likes: '654K',
        comments: '9.8K',
        shares: '21K',
        duration: 90,
      },
      {
        id: 'vid-feed-07',
        creator: 'Priya Sharma',
        handle: '@priyasharma',
        avatar: 'PS',
        caption: 'Bollywood fusion dance at my sister\'s wedding 💃🪔 #bollywood #weddingdance',
        sound: 'Mehndi Laga Ke Rakhna - Lata Mangeshkar',
        likes: '1.8M',
        comments: '11K',
        shares: '67K',
        duration: 45,
      },
      {
        id: 'vid-feed-08',
        creator: 'Jake Thompson',
        handle: '@jakethompson',
        avatar: 'JT',
        caption: 'Buzzer beater from half court at the rec league 🏀🔥 #basketball #buzzerbeater',
        sound: 'NBA on NBC Theme - John Tesh',
        likes: '723K',
        comments: '4.2K',
        shares: '19K',
        duration: 15,
      },
      {
        id: 'vid-feed-09',
        creator: 'Nina Volkov',
        handle: '@ninavolkov',
        avatar: 'NV',
        caption: 'My cat learned to play piano and now she won\'t stop 🐱🎹 #catsoftiktok #piano',
        sound: 'Fur Elise - Beethoven',
        likes: '4.2M',
        comments: '32K',
        shares: '180K',
        duration: 22,
      },
      {
        id: 'vid-feed-10',
        creator: 'Carlos Mendez',
        handle: '@carlosmendez',
        avatar: 'CM',
        caption: 'Street tacos in Mexico City for $1 each 🌮🇲🇽 #streetfood #mexicocity #tacos',
        sound: 'Cumbia Sonidera - Los Ángeles Azules',
        likes: '1.1M',
        comments: '7.3K',
        shares: '45K',
        duration: 60,
      },
      {
        id: 'vid-feed-11',
        creator: 'Hannah Kim',
        handle: '@hannahkim',
        avatar: 'HK',
        caption: 'Day 47 of learning Korean before my trip to Seoul 🇰🇷📚 #languagelearning #korean',
        sound: 'Dynamite - BTS',
        likes: '328K',
        comments: '2.4K',
        shares: '8.7K',
        duration: 36,
      },
      {
        id: 'vid-feed-12',
        creator: 'Tyler Brooks',
        handle: '@tylerbrooks',
        avatar: 'TB',
        caption: 'Surfing at sunrise in Bali was the most peaceful moment of my life 🏄🌅 #surfing #bali',
        sound: 'Ocean Sounds - ambient mix',
        likes: '567K',
        comments: '3.8K',
        shares: '15K',
        duration: 28,
      },
    ],
  },

  /* -----------------------------------------------------------
   * 3. Creator profile
   * --------------------------------------------------------- */
  'tiktok.creator.info': {
    name: 'Maya Chen',
    handle: '@mayachen.cooks',
    avatar: 'MC',
    followers: '4.2M',
    following: 287,
    likes: '89.3M',
    bio: 'Home cook 🍳 | Recipe creator | Cookbook author of "Quick & Wok" 📖 | NYC → worldwide 🌍 | Collabs: maya@mgmt.co',
    verified: true,
  },

  /* -----------------------------------------------------------
   * 4. Creator videos
   * --------------------------------------------------------- */
  'tiktok.creator.videos': {
    items: [
      {
        id: 'vid-creator-01',
        caption: '15-minute spicy ramen hack that broke the internet 🍜🔥 #ramen #noodlehack',
        likes: '1.2M',
        comments: '8.4K',
        shares: '42K',
        duration: 58,
      },
      {
        id: 'vid-creator-02',
        caption: 'One-pan garlic butter shrimp pasta you NEED to try 🦐🍝 #pasta #seafood',
        likes: '987K',
        comments: '6.1K',
        shares: '33K',
        duration: 45,
      },
      {
        id: 'vid-creator-03',
        caption: 'I tried the viral TikTok pasta and added my own twist 🍝✨ #fettuccine #viralrecipe',
        likes: '1.5M',
        comments: '9.7K',
        shares: '51K',
        duration: 52,
      },
      {
        id: 'vid-creator-04',
        caption: '3-ingredient chocolate mousse that tastes like a restaurant dessert 🍫 #dessert #easyrecipe',
        likes: '734K',
        comments: '4.8K',
        shares: '22K',
        duration: 30,
      },
      {
        id: 'vid-creator-05',
        caption: 'Meal prep Sunday: 5 lunches under $20 total 💰🍱 #mealprep #budget',
        likes: '512K',
        comments: '3.2K',
        shares: '14K',
        duration: 72,
      },
      {
        id: 'vid-creator-06',
        caption: 'The crispy rice bowl everyone is asking for 🍚🔥 #crispyrice #bowl',
        likes: '2.1M',
        comments: '13K',
        shares: '78K',
        duration: 65,
      },
      {
        id: 'vid-creator-07',
        caption: 'How to properly season a wok (I was doing it wrong for years) 🍳 #wok #chinesecooking',
        likes: '689K',
        comments: '5.4K',
        shares: '26K',
        duration: 90,
      },
      {
        id: 'vid-creator-08',
        caption: '5-minute breakfast sandwich better than any drive-thru 🥪🍳 #breakfast #sandwich',
        likes: '445K',
        comments: '2.9K',
        shares: '11K',
        duration: 28,
      },
      {
        id: 'vid-creator-09',
        caption: 'I made dumplings from scratch for the first time and cried 🥟😭 #dumplings #homemade',
        likes: '1.3M',
        comments: '8.9K',
        shares: '47K',
        duration: 85,
      },
      {
        id: 'vid-creator-10',
        caption: 'The soup that cured my winter blues 🍲❄️ #soup #comfortfood',
        likes: '823K',
        comments: '5.7K',
        shares: '29K',
        duration: 48,
      },
      {
        id: 'vid-creator-11',
        caption: 'Korean fried chicken at home — crispy, spicy, perfect 🍗🌶️ #koreanfriedchicken #kfc',
        likes: '1.9M',
        comments: '11K',
        shares: '63K',
        duration: 78,
      },
      {
        id: 'vid-creator-12',
        caption: 'My grandma\'s secret dumpling sauce finally revealed 🥢 #familyrecipe #sauce',
        likes: '1.1M',
        comments: '7.2K',
        shares: '38K',
        duration: 40,
      },
    ],
  },

  /* -----------------------------------------------------------
   * 5. Video detail
   * --------------------------------------------------------- */
  'tiktok.video.detail': {
    id: 'vid-feed-01',
    creator: 'Maya Chen',
    handle: '@mayachen.cooks',
    avatar: 'MC',
    caption: '15-minute spicy ramen hack that broke the internet 🍜🔥',
    sound: 'original sound - mayachen.cooks',
    likes: '1.2M',
    comments: '8.4K',
    shares: '42K',
    duration: 58,
    tags: ['ramen', 'noodlehack', 'cooking', 'quickrecipes', 'spicy'],
  },

  /* -----------------------------------------------------------
   * 6. Video comments (with nested replies)
   * --------------------------------------------------------- */
  'tiktok.video.comments': {
    items: [
      {
        id: 'cmt-01',
        author: 'Devon Parker',
        handle: '@devonpark',
        avatar: 'DP',
        text: 'Made this last night and my roommate thought I ordered takeout 😂 unreal',
        likes: '2.1K',
        time: '2h',
        replies: [
          {
            id: 'cmt-01-r1',
            author: 'Maya Chen',
            handle: '@mayachen.cooks',
            avatar: 'MC',
            text: 'Haha that\'s the best compliment! Glad you enjoyed it 🙌',
            likes: '487',
            time: '1h',
          },
          {
            id: 'cmt-01-r2',
            author: 'Riley Adams',
            handle: '@rileylearns',
            avatar: 'RA',
            text: 'Same!! My family was shook',
            likes: '92',
            time: '45m',
          },
        ],
      },
      {
        id: 'cmt-02',
        author: 'Aisha Bello',
        handle: '@aishabello',
        avatar: 'AB',
        text: 'Can I substitute the chili oil for something milder? I\'m a wimp with spice 🥲',
        likes: '342',
        time: '3h',
        replies: [
          {
            id: 'cmt-02-r1',
            author: 'Maya Chen',
            handle: '@mayachen.cooks',
            avatar: 'MC',
            text: 'Absolutely! Try sweet chili sauce or a dollop of honey + soy sauce. Still delicious 🍯',
            likes: '218',
            time: '2h',
          },
        ],
      },
      {
        id: 'cmt-03',
        author: 'Leo Martinez',
        handle: '@leomtz',
        avatar: 'LM',
        text: 'The way the broth coats the noodles is mesmerizing. Need the full recipe ASAP',
        likes: '1.4K',
        time: '4h',
        replies: [
          {
            id: 'cmt-03-r1',
            author: 'Sofia Rossi',
            handle: '@sofiarossi',
            avatar: 'SR',
            text: 'Link in her bio! Just made it 🍜',
            likes: '156',
            time: '3h',
          },
        ],
      },
      {
        id: 'cmt-04',
        author: 'Marcus Webb',
        handle: '@marcuswebb',
        avatar: 'MW',
        text: 'As a broke college student, this just saved my life. $4 and 15 min 🙏',
        likes: '3.8K',
        time: '5h',
        replies: [
          {
            id: 'cmt-04-r1',
            author: 'Priya Sharma',
            handle: '@priyasharma',
            avatar: 'PS',
            text: 'Facts. Ramen hacks are the ultimate survival food',
            likes: '421',
            time: '4h',
          },
          {
            id: 'cmt-04-r2',
            author: 'Jake Thompson',
            handle: '@jakethompson',
            avatar: 'JT',
            text: 'Meal prep this for the whole week 🔥',
            likes: '188',
            time: '3h',
          },
        ],
      },
      {
        id: 'cmt-05',
        author: 'Nina Volkov',
        handle: '@ninavolkov',
        avatar: 'NV',
        text: 'I\'ve watched this 7 times. The sizzle at 0:32 is ASMR perfection',
        likes: '892',
        time: '6h',
        replies: [],
      },
      {
        id: 'cmt-06',
        author: 'Carlos Mendez',
        handle: '@carlosmendez',
        avatar: 'CM',
        text: 'Adding a fried egg on top took this to another level. Trust me 🥚',
        likes: '567',
        time: '7h',
        replies: [
          {
            id: 'cmt-06-r1',
            author: 'Maya Chen',
            handle: '@mayachen.cooks',
            avatar: 'MC',
            text: 'YES. Soft yolk ramen is elite tier 🤌',
            likes: '312',
            time: '6h',
          },
        ],
      },
      {
        id: 'cmt-07',
        author: 'Hannah Kim',
        handle: '@hannahkim',
        avatar: 'HK',
        text: 'Tried with shin black cup noodles and it was a religious experience',
        likes: '1.1K',
        time: '8h',
        replies: [],
      },
      {
        id: 'cmt-08',
        author: 'Tyler Brooks',
        handle: '@tylerbrooks',
        avatar: 'TB',
        text: 'My girlfriend made this for me and I proposed on the spot 💍😂',
        likes: '5.2K',
        time: '10h',
        replies: [
          {
            id: 'cmt-08-r1',
            author: 'Maya Chen',
            handle: '@mayachen.cooks',
            avatar: 'MC',
            text: 'The way to the heart is through ramen, confirmed 💕',
            likes: '1.8K',
            time: '9h',
          },
          {
            id: 'cmt-08-r2',
            author: 'Aisha Bello',
            handle: '@aishabello',
            avatar: 'AB',
            text: 'This is the content I\'m here for 😭❤️',
            likes: '643',
            time: '8h',
          },
          {
            id: 'cmt-08-r3',
            author: 'Leo Martinez',
            handle: '@leomtz',
            avatar: 'LM',
            text: 'Wedding menu: just this ramen. I\'m not joking.',
            likes: '289',
            time: '7h',
          },
        ],
      },
      {
        id: 'cmt-09',
        author: 'Riley Adams',
        handle: '@rileylearns',
        avatar: 'RA',
        text: 'The miso paste ratio is key. I eyeballed it and it was too salty first try 🧂',
        likes: '234',
        time: '12h',
        replies: [],
      },
      {
        id: 'cmt-10',
        author: 'Sofia Rossi',
        handle: '@sofiarossi',
        avatar: 'SR',
        text: 'Made this for my Italian nonna and she said it was "not bad" which is a 10/10',
        likes: '3.4K',
        time: '14h',
        replies: [
          {
            id: 'cmt-10-r1',
            author: 'Marcus Webb',
            handle: '@marcuswebb',
            avatar: 'MW',
            text: 'An Italian nonna approval is worth more than a Michelin star ⭐',
            likes: '876',
            time: '13h',
          },
        ],
      },
      {
        id: 'cmt-11',
        author: 'Jake Thompson',
        handle: '@jakethompson',
        avatar: 'JT',
        text: 'Bro the garlic chili crisp amount was PERFECT. Where do you buy yours?',
        likes: '178',
        time: '16h',
        replies: [],
      },
      {
        id: 'cmt-12',
        author: 'Priya Sharma',
        handle: '@priyasharma',
        avatar: 'PS',
        text: 'I added some bok choy and mushrooms and it was restaurant quality 🥬🍄',
        likes: '612',
        time: '18h',
        replies: [
          {
            id: 'cmt-12-r1',
            author: 'Maya Chen',
            handle: '@mayachen.cooks',
            avatar: 'MC',
            text: 'Love that! Veggies make it a complete meal 🥗',
            likes: '245',
            time: '17h',
          },
        ],
      },
      {
        id: 'cmt-13',
        author: 'Nina Volkov',
        handle: '@ninavolkov',
        avatar: 'NV',
        text: 'The noodle pull at the end should be in a museum 🖼️🍜',
        likes: '1.9K',
        time: '20h',
        replies: [],
      },
      {
        id: 'cmt-14',
        author: 'Carlos Mendez',
        handle: '@carlosmendez',
        avatar: 'CM',
        text: 'Using the instant pot for the broth was a game changer. 5 min pressure cook',
        likes: '445',
        time: '22h',
        replies: [],
      },
      {
        id: 'cmt-15',
        author: 'Hannah Kim',
        handle: '@hannahkim',
        avatar: 'HK',
        text: 'This is my 3rd time making this this week. Send help (and more noodles) 😭🍜',
        likes: '2.7K',
        time: '1d',
        replies: [
          {
            id: 'cmt-15-r1',
            author: 'Tyler Brooks',
            handle: '@tylerbrooks',
            avatar: 'TB',
            text: 'No shame. I\'m on day 4 of the crispy rice bowl from her other video 🍚',
            likes: '534',
            time: '23h',
          },
        ],
      },
    ],
  },

  /* -----------------------------------------------------------
   * 7. Related videos
   * --------------------------------------------------------- */
  'tiktok.video.related': {
    items: [
      {
        id: 'vid-rel-01',
        creator: 'Devon Parker',
        handle: '@devonpark',
        caption: '10-minute miso ramen that tastes like it simmered all day 🍜',
        likes: '432K',
        duration: 42,
      },
      {
        id: 'vid-rel-02',
        creator: 'Aisha Bello',
        handle: '@aishabello',
        caption: 'Spicy tonkotsu ramen from scratch (worth the 8-hour cook) 🍲',
        likes: '1.1M',
        duration: 120,
      },
      {
        id: 'vid-rel-03',
        creator: 'Leo Martinez',
        handle: '@leomtz',
        caption: 'Vegan ramen that meat eaters will love 🌱🍜',
        likes: '287K',
        duration: 55,
      },
      {
        id: 'vid-rel-04',
        creator: 'Sofia Rossi',
        handle: '@sofiarossi',
        caption: 'I tried 5 viral ramen hacks so you don\'t have to 🥢',
        likes: '654K',
        duration: 90,
      },
      {
        id: 'vid-rel-05',
        creator: 'Marcus Webb',
        handle: '@marcuswebb',
        caption: 'College ramen hack: microwave gourmet in 3 minutes 🎓',
        likes: '398K',
        duration: 35,
      },
      {
        id: 'vid-rel-06',
        creator: 'Priya Sharma',
        handle: '@priyasharma',
        caption: 'Spicy noodle challenge — I regret everything 😂🔥',
        likes: '1.8M',
        duration: 28,
      },
      {
        id: 'vid-rel-07',
        creator: 'Jake Thompson',
        handle: '@jakethompson',
        caption: 'Ramen burger: the crossover nobody asked for but everyone needed 🍔🍜',
        likes: '523K',
        duration: 65,
      },
      {
        id: 'vid-rel-08',
        creator: 'Nina Volkov',
        handle: '@ninavolkov',
        caption: 'ASMR ramen making — no talking, just slurps 🎧🥣',
        likes: '2.2M',
        duration: 180,
      },
      {
        id: 'vid-rel-09',
        creator: 'Carlos Mendez',
        handle: '@carlosmendez',
        caption: 'Street-style ramen in Tokyo for $6 🇯🇵🍜',
        likes: '876K',
        duration: 72,
      },
      {
        id: 'vid-rel-10',
        creator: 'Hannah Kim',
        handle: '@hannahkim',
        caption: 'Korean ramyeon with kimchi and cheese — don\'t knock it till you try it 🧀🌶️',
        likes: '1.3M',
        duration: 48,
      },
    ],
  },

  /* -----------------------------------------------------------
   * 8. Trending hashtags
   * --------------------------------------------------------- */
  'tiktok.trending.hashtags': {
    items: [
      { id: 'tag-01', tag: '#ramenhack', posts: '142K', views: '2.1B' },
      { id: 'tag-02', tag: '#cookwithme', posts: '3.4M', views: '18.7B' },
      { id: 'tag-03', tag: '#skatelife', posts: '892K', views: '5.3B' },
      { id: 'tag-04', tag: '#makeuptransition', posts: '1.2M', views: '9.8B' },
      { id: 'tag-05', tag: '#dogsoftiktok', posts: '12.4M', views: '67.2B' },
      { id: 'tag-06', tag: '#travelgram', posts: '8.7M', views: '44.1B' },
      { id: 'tag-07', tag: '#pcbuild', posts: '456K', views: '3.2B' },
      { id: 'tag-08', tag: '#bollywooddance', posts: '678K', views: '4.7B' },
      { id: 'tag-09', tag: '#buzzerbeater', posts: '234K', views: '1.9B' },
      { id: 'tag-10', tag: '#catsoftiktok', posts: '15.2M', views: '82.3B' },
      { id: 'tag-11', tag: '#streetfood', posts: '2.1M', views: '11.4B' },
    ],
  },

  /* -----------------------------------------------------------
   * 9. Trending sounds
   * --------------------------------------------------------- */
  'tiktok.trending.sounds': {
    items: [
      { id: 'snd-01', title: 'original sound - mayachen.cooks', artist: 'Maya Chen', uses: '234K', duration: '0:58' },
      { id: 'snd-02', title: 'Sapphire', artist: 'Beyoncé', uses: '1.2M', duration: '0:30' },
      { id: 'snd-03', title: 'Dynamite', artist: 'BTS', uses: '876K', duration: '0:36' },
      { id: 'snd-04', title: 'Lo-fi Hip Hop Beats', artist: 'chillhop', uses: '3.4M', duration: '0:24' },
      { id: 'snd-05', title: 'La Vie En Rose', artist: 'Louis Armstrong', uses: '567K', duration: '0:18' },
      { id: 'snd-06', title: 'Mehndi Laga Ke Rakhna', artist: 'Lata Mangeshkar', uses: '445K', duration: '0:45' },
      { id: 'snd-07', title: 'NBA on NBC Theme', artist: 'John Tesh', uses: '312K', duration: '0:15' },
      { id: 'snd-08', title: 'Fur Elise', artist: 'Beethoven', uses: '1.8M', duration: '0:22' },
      { id: 'snd-09', title: 'Cumbia Sonidera', artist: 'Los Ángeles Azules', uses: '398K', duration: '1:00' },
      { id: 'snd-10', title: 'Ocean Sounds (ambient mix)', artist: 'Nature Beats', uses: '723K', duration: '0:28' },
      { id: 'snd-11', title: 'Funny Dog Beat', artist: 'viral audio', uses: '2.1M', duration: '0:30' },
    ],
  },

  /* -----------------------------------------------------------
   * 10. Trending creators
   * --------------------------------------------------------- */
  'tiktok.trending.creators': {
    items: [
      { id: 'tcr-01', name: 'Maya Chen', handle: '@mayachen.cooks', avatar: 'MC', followers: '4.2M', verified: true },
      { id: 'tcr-02', name: 'Devon Parker', handle: '@devonpark', avatar: 'DP', followers: '1.8M', verified: false },
      { id: 'tcr-03', name: 'Aisha Bello', handle: '@aishabello', avatar: 'AB', followers: '6.7M', verified: true },
      { id: 'tcr-04', name: 'Leo Martinez', handle: '@leomtz', avatar: 'LM', followers: '3.1M', verified: true },
      { id: 'tcr-05', name: 'Sofia Rossi', handle: '@sofiarossi', avatar: 'SR', followers: '2.4M', verified: false },
      { id: 'tcr-06', name: 'Marcus Webb', handle: '@marcuswebb', avatar: 'MW', followers: '987K', verified: false },
      { id: 'tcr-07', name: 'Priya Sharma', handle: '@priyasharma', avatar: 'PS', followers: '5.3M', verified: true },
      { id: 'tcr-08', name: 'Jake Thompson', handle: '@jakethompson', avatar: 'JT', followers: '1.2M', verified: false },
      { id: 'tcr-09', name: 'Nina Volkov', handle: '@ninavolkov', avatar: 'NV', followers: '8.9M', verified: true },
      { id: 'tcr-10', name: 'Carlos Mendez', handle: '@carlosmendez', avatar: 'CM', followers: '2.7M', verified: true },
      { id: 'tcr-11', name: 'Hannah Kim', handle: '@hannahkim', avatar: 'HK', followers: '1.5M', verified: false },
    ],
  },
};
