export const INSTAGRAM_DATA: Record<string, any> = {
  // ---------------------------------------------------------------------------
  // 1. EXPLORE CATEGORIES
  // ---------------------------------------------------------------------------
  'instagram.categories': [
    { id: 'cat_foryou', name: 'For You' },
    { id: 'cat_travel', name: 'Travel' },
    { id: 'cat_architecture', name: 'Architecture' },
    { id: 'cat_art', name: 'Art' },
    { id: 'cat_style', name: 'Style' },
    { id: 'cat_food', name: 'Food' },
    { id: 'cat_nature', name: 'Nature' },
    { id: 'cat_sports', name: 'Sports' },
    { id: 'cat_music', name: 'Music' },
    { id: 'cat_photography', name: 'Photography' },
  ],

  // ---------------------------------------------------------------------------
  // 2. FEED POSTS
  // ---------------------------------------------------------------------------
  'instagram.feed.posts': [
    {
      id: 'post_001',
      author: 'Maya Chen',
      handle: 'mayawanders',
      avatar: 'https://i.pravatar.cc/150?img=47',
      location: 'Kyoto, Japan',
      caption: 'Cherry blossom season never disappoints. Spent the morning at Maruyama Park and the light was pure magic. 🌸',
      likes: 12847,
      comments: 342,
      time: '2 hours ago',
      mediaType: 'image',
      tags: ['kyoto', 'cherryblossom', 'spring', 'japan', 'travel'],
    },
    {
      id: 'post_002',
      author: 'Marcus Bell',
      handle: 'marcuseats',
      avatar: 'https://i.pravatar.cc/150?img=12',
      location: 'Brooklyn, New York',
      caption: 'New drop at the shop: miso caramel soft serve with burnt honeycomb. Lines are already around the block 🍦',
      likes: 5621,
      comments: 187,
      time: '4 hours ago',
      mediaType: 'image',
      tags: ['food', 'icecream', 'brooklyn', 'dessert'],
    },
    {
      id: 'post_003',
      author: 'Elena Rossi',
      handle: 'elenarossi',
      avatar: 'https://i.pravatar.cc/150?img=23',
      location: 'Amalfi Coast, Italy',
      caption: 'A weekend of cliff diving and limoncello. Swipe for the drone shots of the coastline ⛵',
      likes: 28934,
      comments: 891,
      time: '6 hours ago',
      mediaType: 'carousel',
      tags: ['amalfi', 'italy', 'travel', 'summer', 'coastline'],
    },
    {
      id: 'post_004',
      author: 'Devon Walker',
      handle: 'devonwalks',
      avatar: 'https://i.pravatar.cc/150?img=33',
      location: 'Banff National Park, Canada',
      caption: 'Sunrise over Moraine Lake. Hiked in at 4am and had the entire valley to myself. Worth every cold step.',
      likes: 18450,
      comments: 423,
      time: '8 hours ago',
      mediaType: 'image',
      tags: ['banff', 'canada', 'hiking', 'sunrise', 'nature'],
    },
    {
      id: 'post_005',
      author: 'Priya Sharma',
      handle: 'priyacreates',
      avatar: 'https://i.pravatar.cc/150?img=45',
      location: 'Mumbai, India',
      caption: 'Behind the scenes of today\'s studio shoot. Full process video is up on my YouTube — link in bio 🎥',
      likes: 7320,
      comments: 256,
      time: '10 hours ago',
      mediaType: 'video',
      tags: ['studio', 'photography', 'bts', 'mumbai'],
    },
    {
      id: 'post_006',
      author: 'Jake Morrison',
      handle: 'jakemorrison',
      avatar: 'https://i.pravatar.cc/150?img=15',
      location: 'Bondi Beach, Australia',
      caption: 'Dawn patrol session. Clean 4ft sets rolling through with barely anyone out. Stoke level: maximum 🏄',
      likes: 9876,
      comments: 312,
      time: '12 hours ago',
      mediaType: 'video',
      tags: ['surfing', 'bondi', 'australia', 'ocean', 'dawn'],
    },
    {
      id: 'post_007',
      author: 'Sofia Almeida',
      handle: 'sofiastyles',
      avatar: 'https://i.pravatar.cc/150?img=25',
      location: 'Lisbon, Portugal',
      caption: 'Fall wardrobe transition pieces are live on the shop. This wool blend coat is going to sell out fast 🧥',
      likes: 4521,
      comments: 198,
      time: '14 hours ago',
      mediaType: 'image',
      tags: ['fashion', 'style', 'lisbon', 'ootd', 'fall'],
    },
    {
      id: 'post_008',
      author: 'Tomás Herrera',
      handle: 'tomasherrera',
      avatar: 'https://i.pravatar.cc/150?img=51',
      location: 'Mexico City, Mexico',
      caption: 'Street art tour through Roma Norte. The murals here tell stories you won\'t find in any gallery 🎨',
      likes: 11203,
      comments: 367,
      time: '16 hours ago',
      mediaType: 'carousel',
      tags: ['streetart', 'mexicocity', 'roma', 'art', 'travel'],
    },
    {
      id: 'post_009',
      author: 'Aisha Bello',
      handle: 'aishabakes',
      avatar: 'https://i.pravatar.cc/150?img=44',
      location: 'Lagos, Nigeria',
      caption: 'Sourdough workshop this Saturday is fully booked! Next session opens for registration on Friday 🍞',
      likes: 3287,
      comments: 145,
      time: '18 hours ago',
      mediaType: 'image',
      tags: ['baking', 'sourdough', 'lagos', 'workshop'],
    },
    {
      id: 'post_010',
      author: 'Liam O\'Brien',
      handle: 'liamobrien',
      avatar: 'https://i.pravatar.cc/150?img=13',
      location: 'Dublin, Ireland',
      caption: 'New single "Tide Lines" drops Friday. Here\'s a 30 second teaser from the recording session 🎸',
      likes: 15643,
      comments: 521,
      time: '20 hours ago',
      mediaType: 'video',
      tags: ['music', 'indie', 'dublin', 'newrelease'],
    },
    {
      id: 'post_011',
      author: 'Yuki Tanaka',
      handle: 'yukitanaka',
      avatar: 'https://i.pravatar.cc/150?img=48',
      location: 'Tokyo, Japan',
      caption: 'Minimalist living room refresh. Swapped the coffee table for a low oak piece and the whole space changed 🏠',
      likes: 8901,
      comments: 278,
      time: '22 hours ago',
      mediaType: 'image',
      tags: ['interior', 'minimalist', 'tokyo', 'design', 'home'],
    },
    {
      id: 'post_012',
      author: 'Carlos Mendes',
      handle: 'carlosmendes',
      avatar: 'https://i.pravatar.cc/150?img=53',
      location: 'São Paulo, Brazil',
      caption: 'Match day at Morumbi. The energy in the stadium when we scored the equalizer was absolutely unreal ⚽',
      likes: 21345,
      comments: 634,
      time: '1 day ago',
      mediaType: 'video',
      tags: ['football', 'saopaulo', 'matchday', 'sports'],
    },
  ],

  // ---------------------------------------------------------------------------
  // 3. STORIES
  // ---------------------------------------------------------------------------
  'instagram.stories': [
    { id: 'story_001', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', seen: false },
    { id: 'story_002', author: 'Marcus Bell', handle: 'marcuseats', avatar: 'https://i.pravatar.cc/150?img=12', seen: false },
    { id: 'story_003', author: 'Elena Rossi', handle: 'elenarossi', avatar: 'https://i.pravatar.cc/150?img=23', seen: false },
    { id: 'story_004', author: 'Devon Walker', handle: 'devonwalks', avatar: 'https://i.pravatar.cc/150?img=33', seen: true },
    { id: 'story_005', author: 'Priya Sharma', handle: 'priyacreates', avatar: 'https://i.pravatar.cc/150?img=45', seen: false },
    { id: 'story_006', author: 'Jake Morrison', handle: 'jakemorrison', avatar: 'https://i.pravatar.cc/150?img=15', seen: true },
    { id: 'story_007', author: 'Sofia Almeida', handle: 'sofiastyles', avatar: 'https://i.pravatar.cc/150?img=25', seen: false },
    { id: 'story_008', author: 'Tomás Herrera', handle: 'tomasherrera', avatar: 'https://i.pravatar.cc/150?img=51', seen: true },
    { id: 'story_009', author: 'Aisha Bello', handle: 'aishabakes', avatar: 'https://i.pravatar.cc/150?img=44', seen: false },
    { id: 'story_010', author: 'Liam O\'Brien', handle: 'liamobrien', avatar: 'https://i.pravatar.cc/150?img=13', seen: true },
    { id: 'story_011', author: 'Yuki Tanaka', handle: 'yukitanaka', avatar: 'https://i.pravatar.cc/150?img=48', seen: false },
  ],

  // ---------------------------------------------------------------------------
  // 4. PROFILE INFO
  // ---------------------------------------------------------------------------
  'instagram.profile.info': {
    name: 'Maya Chen',
    handle: 'mayawanders',
    avatar: 'https://i.pravatar.cc/150?img=47',
    bio: 'Travel & lifestyle photographer 🌍\nCurrently based in Tokyo\nWorkshops & prints ↓',
    posts: 1284,
    followers: 247890,
    following: 891,
    verified: true,
    category: 'Digital Creator',
  },

  // ---------------------------------------------------------------------------
  // 5. PROFILE POSTS
  // ---------------------------------------------------------------------------
  'instagram.profile.posts': [
    { id: 'upost_001', caption: 'Morning fog rolling through the bamboo grove in Arashiyama. Shot on Sony A7IV with 24-70mm.', likes: 8432, comments: 231, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/bamboo/400/400' },
    { id: 'upost_002', caption: 'Street food market in Osaka. The takoyaki here is the best I\'ve had on this entire trip.', likes: 5210, comments: 142, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/osaka/400/400' },
    { id: 'upost_003', caption: 'Time-lapse of the Shibuya crossing at golden hour. Full video on YouTube.', likes: 12034, comments: 389, mediaType: 'video', thumbnail: 'https://picsum.photos/seed/shibuya/400/400' },
    { id: 'upost_004', caption: 'Tea ceremony in Gion. Such a meditative experience learning from a 4th generation tea master.', likes: 6789, comments: 187, mediaType: 'carousel', thumbnail: 'https://picsum.photos/seed/teaceremony/400/400' },
    { id: 'upost_005', caption: 'Hiked Mount Kurama at dawn. The cedar forest felt ancient and alive in a way I can\'t describe.', likes: 9123, comments: 245, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/kurama/400/400' },
    { id: 'upost_006', caption: 'Ramen hunt day 3. This tonkotsu broth was simmered for 18 hours. Worth the train ride to Hakata.', likes: 7456, comments: 198, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/ramen/400/400' },
    { id: 'upost_007', caption: 'Behind the scenes from my photography workshop last weekend. Such an incredible group!', likes: 4321, comments: 112, mediaType: 'carousel', thumbnail: 'https://picsum.photos/seed/workshop/400/400' },
    { id: 'upost_008', caption: 'Fushimi Inari at 5am before the crowds. The thousands of torii gates go on forever.', likes: 15678, comments: 412, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/fushimi/400/400' },
    { id: 'upost_009', caption: 'Neon streets of Shinjuku at night. Long exposure to capture the light trails from the traffic.', likes: 11023, comments: 298, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/shinjuku/400/400' },
    { id: 'upost_010', caption: 'Cherry blossom edit from last week is finally done. Swipe to see the full series 🌸', likes: 18934, comments: 521, mediaType: 'carousel', thumbnail: 'https://picsum.photos/seed/blossom/400/400' },
    { id: 'upost_011', caption: 'Onsen evening in Hakone. The mountain view from the outdoor bath was unreal.', likes: 7890, comments: 167, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/onsen/400/400' },
    { id: 'upost_012', caption: 'Quick portrait session with a local artisan who makes traditional Kyoto dolls. Inspiring craft.', likes: 6543, comments: 143, mediaType: 'image', thumbnail: 'https://picsum.photos/seed/artisan/400/400' },
  ],

  // ---------------------------------------------------------------------------
  // 6. POST DETAIL
  // ---------------------------------------------------------------------------
  'instagram.post.detail': {
    id: 'post_001',
    author: 'Maya Chen',
    handle: 'mayawanders',
    avatar: 'https://i.pravatar.cc/150?img=47',
    location: 'Kyoto, Japan',
    caption: 'Cherry blossom season never disappoints. Spent the morning at Maruyama Park and the light was pure magic. 🌸 Shot on Sony A7IV with the 85mm f/1.4. The weeping cherry tree at the center of the park was in full bloom and the crowd was surprisingly manageable if you arrive before 7am.',
    likes: 12847,
    comments: 342,
    time: '2 hours ago',
    mediaType: 'image',
    tags: ['kyoto', 'cherryblossom', 'spring', 'japan', 'travel', 'sony', 'photography'],
  },

  // ---------------------------------------------------------------------------
  // 7. POST COMMENTS
  // ---------------------------------------------------------------------------
  'instagram.post.comments': [
    {
      id: 'comment_001',
      author: 'Elena Rossi',
      handle: 'elenarossi',
      avatar: 'https://i.pravatar.cc/150?img=23',
      text: 'This is absolutely stunning! The light is perfect. Was this handheld or on a tripod?',
      likes: 234,
      time: '1 hour ago',
      replies: [
        { id: 'reply_001a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'Tripod for this one. The 85mm at f/1.4 needs steady hands otherwise!', likes: 45, time: '58 minutes ago' },
        { id: 'reply_001b', author: 'Elena Rossi', handle: 'elenarossi', avatar: 'https://i.pravatar.cc/150?img=23', text: 'Makes sense. The bokeh is so creamy 😍', likes: 12, time: '50 minutes ago' },
      ],
    },
    {
      id: 'comment_002',
      author: 'Devon Walker',
      handle: 'devonwalks',
      avatar: 'https://i.pravatar.cc/150?img=33',
      text: 'Maruyama Park is incredible. I was there last year and the evening illumination is something else too.',
      likes: 156,
      time: '1 hour ago',
      replies: [
        { id: 'reply_002a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'Yes! The illumination runs until 9pm. Planning to go back for that later this week.', likes: 28, time: '45 minutes ago' },
      ],
    },
    {
      id: 'comment_003',
      author: 'Marcus Bell',
      handle: 'marcuseats',
      avatar: 'https://i.pravatar.cc/150?img=12',
      text: 'Adding Kyoto to my travel list immediately. Any food recommendations while I\'m there?',
      likes: 89,
      time: '2 hours ago',
      replies: [
        { id: 'reply_003a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'Hit up Nishiki Market for street food and Issen Yoshoku for the okonomiyaki!', likes: 34, time: '1 hour ago' },
        { id: 'reply_003b', author: 'Marcus Bell', handle: 'marcuseats', avatar: 'https://i.pravatar.cc/150?img=12', text: 'Bookmarked. Thank you!', likes: 5, time: '55 minutes ago' },
      ],
    },
    {
      id: 'comment_004',
      author: 'Sofia Almeida',
      handle: 'sofiastyles',
      avatar: 'https://i.pravatar.cc/150?img=25',
      text: 'The composition here is textbook. Love how you framed the tree against the soft background.',
      likes: 112,
      time: '2 hours ago',
      replies: [],
    },
    {
      id: 'comment_005',
      author: 'Liam O\'Brien',
      handle: 'liamobrien',
      avatar: 'https://i.pravatar.cc/150?img=13',
      text: 'This just became my phone wallpaper. Hope that\'s okay 😄',
      likes: 78,
      time: '2 hours ago',
      replies: [
        { id: 'reply_005a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'Go for it! High res version is on my prints store if you want it too 🙌', likes: 22, time: '1 hour ago' },
      ],
    },
    {
      id: 'comment_006',
      author: 'Priya Sharma',
      handle: 'priyacreates',
      avatar: 'https://i.pravatar.cc/150?img=45',
      text: 'The color grading on this is so warm and natural. What\'s your workflow?',
      likes: 67,
      time: '2 hours ago',
      replies: [
        { id: 'reply_006a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'Lightroom with my custom preset (link in bio) then minor tweaks in Photoshop for the highlights.', likes: 19, time: '1 hour ago' },
      ],
    },
    {
      id: 'comment_007',
      author: 'Jake Morrison',
      handle: 'jakemorrison',
      avatar: 'https://i.pravatar.cc/150?img=15',
      text: 'Japan in spring is unbeatable. Surfing was terrible but the scenery made up for it 😂',
      likes: 143,
      time: '3 hours ago',
      replies: [],
    },
    {
      id: 'comment_008',
      author: 'Aisha Bello',
      handle: 'aishabakes',
      avatar: 'https://i.pravatar.cc/150?img=44',
      text: 'The pink against the green is such a perfect contrast. Nature really is the best designer.',
      likes: 54,
      time: '3 hours ago',
      replies: [],
    },
    {
      id: 'comment_009',
      author: 'Tomás Herrera',
      handle: 'tomasherrera',
      avatar: 'https://i.pravatar.cc/150?img=51',
      text: 'Saving this for my Japan trip in May. Probably missed the blossoms but Kyoto looks amazing year round.',
      likes: 41,
      time: '3 hours ago',
      replies: [
        { id: 'reply_009a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'May is great for fresh greenery and fewer crowds. You\'ll love it!', likes: 15, time: '2 hours ago' },
      ],
    },
    {
      id: 'comment_010',
      author: 'Yuki Tanaka',
      handle: 'yukitanaka',
      avatar: 'https://i.pravatar.cc/150?img=48',
      text: 'As a local I walk past this tree every day and still stop to admire it. Glad visitors get to see it too!',
      likes: 201,
      time: '3 hours ago',
      replies: [
        { id: 'reply_010a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'You\'re so lucky to live here! Kyoto is magical.', likes: 31, time: '2 hours ago' },
        { id: 'reply_010b', author: 'Yuki Tanaka', handle: 'yukitanaka', avatar: 'https://i.pravatar.cc/150?img=48', text: 'Come visit in autumn too — the maples are even better 🍁', likes: 18, time: '2 hours ago' },
      ],
    },
    {
      id: 'comment_011',
      author: 'Carlos Mendes',
      handle: 'carlosmendes',
      avatar: 'https://i.pravatar.cc/150?img=53',
      text: 'Incredible shot! What time did you get there to avoid the crowds?',
      likes: 38,
      time: '4 hours ago',
      replies: [
        { id: 'reply_011a', author: 'Maya Chen', handle: 'mayawanders', avatar: 'https://i.pravatar.cc/150?img=47', text: 'Arrived at 6:15am. By 8am the tour buses start rolling in.', likes: 24, time: '3 hours ago' },
      ],
    },
    {
      id: 'comment_012',
      author: 'Sofia Almeida',
      handle: 'sofiastyles',
      avatar: 'https://i.pravatar.cc/150?img=25',
      text: 'Just shared this to my stories. The aesthetic is everything right now.',
      likes: 27,
      time: '4 hours ago',
      replies: [],
    },
    {
      id: 'comment_013',
      author: 'Devon Walker',
      handle: 'devonwalks',
      avatar: 'https://i.pravatar.cc/150?img=33',
      text: '85mm f/1.4 is such a dream lens for this kind of shot. The compression is chef\'s kiss.',
      likes: 63,
      time: '4 hours ago',
      replies: [],
    },
    {
      id: 'comment_014',
      author: 'Elena Rossi',
      handle: 'elenarossi',
      avatar: 'https://i.pravatar.cc/150?img=23',
      text: 'Following your Japan series religiously now. Keep them coming!',
      likes: 49,
      time: '5 hours ago',
      replies: [],
    },
    {
      id: 'comment_015',
      author: 'Marcus Bell',
      handle: 'marcuseats',
      avatar: 'https://i.pravatar.cc/150?img=12',
      text: 'The weeping cherry is the star of Maruyama for sure. Great capture of it in peak bloom.',
      likes: 35,
      time: '5 hours ago',
      replies: [],
    },
  ],

  // ---------------------------------------------------------------------------
  // 8. EXPLORE GRID
  // ---------------------------------------------------------------------------
  'instagram.explore.grid': [
    { id: 'exp_001', author: 'Maya Chen', handle: 'mayawanders', thumbnail: 'https://picsum.photos/seed/exp1/400/400', likes: 12847, comments: 342, mediaType: 'image' },
    { id: 'exp_002', author: 'Marcus Bell', handle: 'marcuseats', thumbnail: 'https://picsum.photos/seed/exp2/400/400', likes: 5621, comments: 187, mediaType: 'image' },
    { id: 'exp_003', author: 'Elena Rossi', handle: 'elenarossi', thumbnail: 'https://picsum.photos/seed/exp3/400/400', likes: 28934, comments: 891, mediaType: 'carousel' },
    { id: 'exp_004', author: 'Devon Walker', handle: 'devonwalks', thumbnail: 'https://picsum.photos/seed/exp4/400/400', likes: 18450, comments: 423, mediaType: 'image' },
    { id: 'exp_005', author: 'Priya Sharma', handle: 'priyacreates', thumbnail: 'https://picsum.photos/seed/exp5/400/400', likes: 7320, comments: 256, mediaType: 'video' },
    { id: 'exp_006', author: 'Jake Morrison', handle: 'jakemorrison', thumbnail: 'https://picsum.photos/seed/exp6/400/400', likes: 9876, comments: 312, mediaType: 'video' },
    { id: 'exp_007', author: 'Sofia Almeida', handle: 'sofiastyles', thumbnail: 'https://picsum.photos/seed/exp7/400/400', likes: 4521, comments: 198, mediaType: 'image' },
    { id: 'exp_008', author: 'Tomás Herrera', handle: 'tomasherrera', thumbnail: 'https://picsum.photos/seed/exp8/400/400', likes: 11203, comments: 367, mediaType: 'carousel' },
    { id: 'exp_009', author: 'Aisha Bello', handle: 'aishabakes', thumbnail: 'https://picsum.photos/seed/exp9/400/400', likes: 3287, comments: 145, mediaType: 'image' },
    { id: 'exp_010', author: 'Liam O\'Brien', handle: 'liamobrien', thumbnail: 'https://picsum.photos/seed/exp10/400/400', likes: 15643, comments: 521, mediaType: 'video' },
    { id: 'exp_011', author: 'Yuki Tanaka', handle: 'yukitanaka', thumbnail: 'https://picsum.photos/seed/exp11/400/400', likes: 8901, comments: 278, mediaType: 'image' },
    { id: 'exp_012', author: 'Carlos Mendes', handle: 'carlosmendes', thumbnail: 'https://picsum.photos/seed/exp12/400/400', likes: 21345, comments: 634, mediaType: 'video' },
  ],

  // ---------------------------------------------------------------------------
  // 9. SUGGESTED ACCOUNTS
  // ---------------------------------------------------------------------------
  'instagram.suggested': [
    { id: 'sug_001', name: 'Nadia Volkov', handle: 'nadiavolkov', avatar: 'https://i.pravatar.cc/150?img=20', verified: true, mutuals: 12, bio: 'Fashion editor at Moda Magazine. Style is a language.' },
    { id: 'sug_002', name: 'Ravi Kapoor', handle: 'ravikapoor', avatar: 'https://i.pravatar.cc/150?img=11', verified: false, mutuals: 8, bio: 'Street photographer capturing Mumbai one frame at a time.' },
    { id: 'sug_003', name: 'Greta Lindqvist', handle: 'gretalin', avatar: 'https://i.pravatar.cc/150?img=31', verified: true, mutuals: 23, bio: 'Nordic interior designer. Less is more, but better.' },
    { id: 'sug_004', name: 'Andre Costa', handle: 'andrecosta', avatar: 'https://i.pravatar.cc/150?img=52', verified: false, mutuals: 5, bio: 'Chef de cuisine. Brazilian flavors, French techniques.' },
    { id: 'sug_005', name: 'Hannah Park', handle: 'hannahpark', avatar: 'https://i.pravatar.cc/150?img=49', verified: true, mutuals: 31, bio: 'Travel writer. 64 countries and counting. Tips & stories below.' },
    { id: 'sug_006', name: 'Olu Adesanya', handle: 'oluadesanya', avatar: 'https://i.pravatar.cc/150?img=43', verified: false, mutuals: 4, bio: 'Afrobeat producer & DJ. New EP out now.' },
    { id: 'sug_007', name: 'Clara Moreau', handle: 'claramoreau', avatar: 'https://i.pravatar.cc/150?img=24', verified: true, mutuals: 18, bio: 'Ceramicist & sculptor. Handmade pieces, slow craft.' },
    { id: 'sug_008', name: 'Ben Carter', handle: 'bencarter', avatar: 'https://i.pravatar.cc/150?img=14', verified: false, mutuals: 7, bio: 'Trail runner & adventure filmmaker. Mountains > everything.' },
    { id: 'sug_009', name: 'Mei Lin', handle: 'meilin', avatar: 'https://i.pravatar.cc/150?img=41', verified: true, mutuals: 15, bio: 'Food stylist & recipe developer. Cookbook coming spring 2026.' },
    { id: 'sug_010', name: 'Diego Fernández', handle: 'diegofdez', avatar: 'https://i.pravatar.cc/150?img=54', verified: false, mutuals: 6, bio: 'Architectural photographer. Lines, light, and concrete.' },
  ],

  // ---------------------------------------------------------------------------
  // 10. NOTIFICATIONS
  // ---------------------------------------------------------------------------
  'instagram.notifications': [
    { id: 'notif_001', type: 'like', actor: 'Elena Rossi', handle: 'elenarossi', avatar: 'https://i.pravatar.cc/150?img=23', text: 'liked your photo.', time: '5 minutes ago', postThumbnail: 'https://picsum.photos/seed/bamboo/100/100' },
    { id: 'notif_002', type: 'comment', actor: 'Devon Walker', handle: 'devonwalks', avatar: 'https://i.pravatar.cc/150?img=33', text: 'commented: "This is unreal! Where exactly was this taken?"', time: '12 minutes ago', postThumbnail: 'https://picsum.photos/seed/fushimi/100/100' },
    { id: 'notif_003', type: 'follow', actor: 'Nadia Volkov', handle: 'nadiavolkov', avatar: 'https://i.pravatar.cc/150?img=20', text: 'started following you.', time: '25 minutes ago', postThumbnail: null },
    { id: 'notif_004', type: 'like', actor: 'Marcus Bell', handle: 'marcuseats', avatar: 'https://i.pravatar.cc/150?img=12', text: 'and 247 others liked your photo.', time: '40 minutes ago', postThumbnail: 'https://picsum.photos/seed/blossom/100/100' },
    { id: 'notif_005', type: 'mention', actor: 'Priya Sharma', handle: 'priyacreates', avatar: 'https://i.pravatar.cc/150?img=45', text: 'mentioned you in a comment: "Learned so much from @mayawanders workshop!"', time: '1 hour ago', postThumbnail: 'https://picsum.photos/seed/workshop/100/100' },
    { id: 'notif_006', type: 'follow', actor: 'Hannah Park', handle: 'hannahpark', avatar: 'https://i.pravatar.cc/150?img=49', text: 'started following you.', time: '2 hours ago', postThumbnail: null },
    { id: 'notif_007', type: 'like', actor: 'Sofia Almeida', handle: 'sofiastyles', avatar: 'https://i.pravatar.cc/150?img=25', text: 'liked your video.', time: '3 hours ago', postThumbnail: 'https://picsum.photos/seed/shibuya/100/100' },
    { id: 'notif_008', type: 'comment', actor: 'Liam O\'Brien', handle: 'liamobrien', avatar: 'https://i.pravatar.cc/150?img=13', text: 'commented: "Need to collab on a music video sometime 🎬"', time: '4 hours ago', postThumbnail: 'https://picsum.photos/seed/shinjuku/100/100' },
    { id: 'notif_009', type: 'follow', actor: 'Greta Lindqvist', handle: 'gretalin', avatar: 'https://i.pravatar.cc/150?img=31', text: 'and 18 others started following you.', time: '5 hours ago', postThumbnail: null },
    { id: 'notif_010', type: 'like', actor: 'Yuki Tanaka', handle: 'yukitanaka', avatar: 'https://i.pravatar.cc/150?img=48', text: 'liked your photo.', time: '6 hours ago', postThumbnail: 'https://picsum.photos/seed/teaceremony/100/100' },
    { id: 'notif_011', type: 'mention', actor: 'Tomás Herrera', handle: 'tomasherrera', avatar: 'https://i.pravatar.cc/150?img=51', text: 'tagged you in a post: "Street art tour inspired by @mayawanders travel guides"', time: '8 hours ago', postThumbnail: 'https://picsum.photos/seed/exp8/100/100' },
    { id: 'notif_012', type: 'comment', actor: 'Aisha Bello', handle: 'aishabakes', avatar: 'https://i.pravatar.cc/150?img=44', text: 'commented: "Your food photography tips changed my whole game 🙏"', time: '10 hours ago', postThumbnail: 'https://picsum.photos/seed/ramen/100/100' },
  ],
};
