export const TESLA_DATA: Record<string, any> = {
  // ---------------------------------------------------------------------------
  // 1. VEHICLE CATEGORIES
  // ---------------------------------------------------------------------------
  'tesla.categories': [
    { id: 'cat_sedan', name: 'Sedans', description: 'Performance luxury sedans' },
    { id: 'cat_suv', name: 'SUVs', description: 'All-electric utility vehicles' },
    { id: 'cat_truck', name: 'Trucks', description: 'Built for any terrain' },
    { id: 'cat_roadster', name: 'Roadsters', description: 'All-electric supercars' },
    { id: 'cat_charging', name: 'Charging', description: 'Supercharger network' },
    { id: 'cat_energy', name: 'Energy', description: 'Solar and Powerwall' },
    { id: 'cat_accessories', name: 'Accessories', description: 'Vehicle accessories' },
    { id: 'cat_apparel', name: 'Apparel', description: 'Lifestyle and apparel' },
  ],

  // ---------------------------------------------------------------------------
  // 2. VEHICLE MODELS
  // ---------------------------------------------------------------------------
  'tesla.models': [
    {
      id: 'model_s',
      name: 'Model S',
      trim: 'Plaid',
      price: 89990,
      range: '405 mi',
      topSpeed: '200 mph',
      acceleration: '1.99 s',
      power: '1,020 hp',
      drivetrain: 'Tri-Motor AWD',
      seating: 5,
      image: 'https://picsum.photos/seed/models/600/400',
      category: 'cat_sedan',
      tagline: 'The ultimate performance sedan',
    },
    {
      id: 'model_3',
      name: 'Model 3',
      trim: 'Performance',
      price: 38990,
      range: '358 mi',
      topSpeed: '162 mph',
      acceleration: '2.9 s',
      power: '480 hp',
      drivetrain: 'Dual-Motor AWD',
      seating: 5,
      image: 'https://picsum.photos/seed/model3/600/400',
      category: 'cat_sedan',
      tagline: 'The everyday sports sedan',
    },
    {
      id: 'model_x',
      name: 'Model X',
      trim: 'Plaid',
      price: 99990,
      range: '348 mi',
      topSpeed: '163 mph',
      acceleration: '2.5 s',
      power: '1,020 hp',
      drivetrain: 'Tri-Motor AWD',
      seating: 7,
      image: 'https://picsum.photos/seed/modelx/600/400',
      category: 'cat_suv',
      tagline: 'The safest SUV ever',
    },
    {
      id: 'model_y',
      name: 'Model Y',
      trim: 'Long Range',
      price: 44990,
      range: '330 mi',
      topSpeed: '135 mph',
      acceleration: '3.5 s',
      power: '456 hp',
      drivetrain: 'Dual-Motor AWD',
      seating: 7,
      image: 'https://picsum.photos/seed/modely/600/400',
      category: 'cat_suv',
      tagline: 'The most versatile Tesla',
    },
    {
      id: 'cybertruck',
      name: 'Cybertruck',
      trim: 'All-Terrain',
      price: 69990,
      range: '340 mi',
      topSpeed: '130 mph',
      acceleration: '2.6 s',
      power: '845 hp',
      drivetrain: 'Tri-Motor AWD',
      seating: 6,
      image: 'https://picsum.photos/seed/cybertruck/600/400',
      category: 'cat_truck',
      tagline: 'Built for any planet',
    },
    {
      id: 'roadster',
      name: 'Roadster',
      trim: 'Founders Series',
      price: 200000,
      range: '620 mi',
      topSpeed: '250+ mph',
      acceleration: '1.9 s',
      power: '10,000 Nm',
      drivetrain: 'Tri-Motor AWD',
      seating: 4,
      image: 'https://picsum.photos/seed/roadster/600/400',
      category: 'cat_roadster',
      tagline: 'The quickest car in the world',
    },
  ],

  // ---------------------------------------------------------------------------
  // 3. PRODUCT DETAIL (single vehicle)
  // ---------------------------------------------------------------------------
  'tesla.product.detail': {
    id: 'model_s',
    name: 'Model S',
    trim: 'Plaid',
    price: 89990,
    range: '405 mi',
    topSpeed: '200 mph',
    acceleration: '1.99 s',
    power: '1,020 hp',
    drivetrain: 'Tri-Motor AWD',
    seating: 5,
    dragCoefficient: '0.208 Cd',
    weight: '4,766 lbs',
    cargo: '28 cu ft',
    warranty: '8 years or 150,000 miles',
    images: [
      'https://picsum.photos/seed/modelsmain/800/500',
      'https://picsum.photos/seed/models1/200/120',
      'https://picsum.photos/seed/models2/200/120',
      'https://picsum.photos/seed/models3/200/120',
      'https://picsum.photos/seed/models4/200/120',
    ],
    features: [
      'Tri-motor all-wheel drive',
      '0-60 mph in 1.99 seconds',
      '200 mph top speed',
      '405 miles EPA range',
      '17" cinematic display',
      'Gaming computer with 10 teraflops',
      'HEPA filtration',
      'Glass roof with UV protection',
    ],
  },

  // ---------------------------------------------------------------------------
  // 3b. PRODUCT DETAIL nested arrays — flat keys for item templates
  // ---------------------------------------------------------------------------
  'tesla.product.images': [
    'https://picsum.photos/seed/modelsmain/800/500',
    'https://picsum.photos/seed/models1/200/120',
    'https://picsum.photos/seed/models2/200/120',
    'https://picsum.photos/seed/models3/200/120',
    'https://picsum.photos/seed/models4/200/120',
  ],
  'tesla.product.features': [
    'Tri-motor all-wheel drive',
    '0-60 mph in 1.99 seconds',
    '200 mph top speed',
    '405 miles EPA range',
    '17" cinematic display',
    'Gaming computer with 10 teraflops',
    'HEPA filtration',
    'Glass roof with UV protection',
  ],

  // ---------------------------------------------------------------------------
  // 4. CONFIGURATION OPTIONS
  // ---------------------------------------------------------------------------
  'tesla.product.config': {
    paint: [
      { id: 'paint_white', name: 'Pearl White Multi-Coat', price: 0, hex: '#f7f7f7' },
      { id: 'paint_black', name: 'Solid Black', price: 0, hex: '#000000' },
      { id: 'paint_silver', name: 'Midnight Silver Metallic', price: 1000, hex: '#5c5c5c' },
      { id: 'paint_blue', name: 'Deep Blue Metallic', price: 1000, hex: '#1a3a5c' },
      { id: 'paint_red', name: 'Red Multi-Coat', price: 2500, hex: '#e31937' },
    ],
    wheels: [
      { id: 'wheels_19', name: '19" Tempest Wheels', price: 0 },
      { id: 'wheels_21', name: '21" Arachnid Wheels', price: 4500 },
    ],
    interior: [
      { id: 'interior_black', name: 'All Black', price: 0 },
      { id: 'interior_bw', name: 'Black & White', price: 2000 },
      { id: 'interior_cream', name: 'Cream', price: 3000 },
    ],
    autopilot: [
      { id: 'ap_basic', name: 'Autopilot', price: 0, included: true },
      { id: 'ap_enhanced', name: 'Enhanced Autopilot', price: 6000 },
      { id: 'ap_fsd', name: 'Full Self-Driving Capability', price: 15000 },
    ],
  },

  /* 4b. Config nested arrays — flat keys for item templates */
  'tesla.config.paint': [
    { id: 'paint_white', name: 'Pearl White Multi-Coat', price: 0, hex: '#f7f7f7' },
    { id: 'paint_black', name: 'Solid Black', price: 0, hex: '#000000' },
    { id: 'paint_silver', name: 'Midnight Silver Metallic', price: 1000, hex: '#5c5c5c' },
    { id: 'paint_blue', name: 'Deep Blue Metallic', price: 1000, hex: '#1a3a5c' },
    { id: 'paint_red', name: 'Red Multi-Coat', price: 2500, hex: '#e31937' },
  ],
  'tesla.config.wheels': [
    { id: 'wheels_19', name: '19" Tempest Wheels', price: 0 },
    { id: 'wheels_21', name: '21" Arachnid Wheels', price: 4500 },
  ],
  'tesla.config.interior': [
    { id: 'interior_black', name: 'All Black', price: 0 },
    { id: 'interior_bw', name: 'Black & White', price: 2000 },
    { id: 'interior_cream', name: 'Cream', price: 3000 },
  ],
  'tesla.config.autopilot': [
    { id: 'ap_basic', name: 'Autopilot', price: 0, included: true },
    { id: 'ap_enhanced', name: 'Enhanced Autopilot', price: 6000 },
    { id: 'ap_fsd', name: 'Full Self-Driving Capability', price: 15000 },
  ],

  // ---------------------------------------------------------------------------
  // 5. PRODUCT REVIEWS (15+ with replies)
  // ---------------------------------------------------------------------------
  'tesla.product.reviews': [
    {
      id: 'rev_001',
      author: 'James Whitfield',
      avatar: 'https://i.pravatar.cc/150?img=12',
      rating: 5,
      time: '2 weeks ago',
      title: '8 months in and still incredible',
      text: 'After 8 months and 12,000 miles, the Plaid continues to blow me away. The acceleration never gets old and the range is real — I regularly hit 380 miles on a full charge.',
      verified: true,
      replies: [
        { id: 'rev_001_r1', author: 'Tesla Team', avatar: 'https://i.pravatar.cc/150?img=68', text: 'Thanks for the review, James! Glad you\'re enjoying the Plaid experience.', time: '1 week ago' },
      ],
    },
    {
      id: 'rev_002',
      author: 'Sofia Martinez',
      avatar: 'https://i.pravatar.cc/150?img=25',
      rating: 5,
      time: '1 month ago',
      title: 'Yoke took a week, now I love it',
      text: 'The yoke took about a week to get used to but now I prefer it. Autopilot on the highway is genuinely stress-reducing. Build quality on my 2024 is excellent.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_003',
      author: 'David Chen',
      avatar: 'https://i.pravatar.cc/150?img=33',
      rating: 5,
      time: '1 month ago',
      title: 'Track mode is unreal',
      text: 'Track mode at Laguna Seca was an experience I\'ll never forget. The car handles like it\'s on rails. Only complaint is the rear seat headroom for adults.',
      verified: true,
      replies: [
        { id: 'rev_003_r1', author: 'Marcus Lee', avatar: 'https://i.pravatar.cc/150?img=14', text: 'Same experience at Sonoma. The regen braking takes a session to master but then it\'s perfect.', time: '3 weeks ago' },
      ],
    },
    {
      id: 'rev_004',
      author: 'Emily Roberts',
      avatar: 'https://i.pravatar.cc/150?img=23',
      rating: 4,
      time: '2 months ago',
      title: 'Amazing car, app could be better',
      text: 'The car itself is a marvel of engineering. The mobile app sometimes takes a long time to connect which is frustrating when I\'m trying to pre-condition the cabin.',
      verified: true,
      replies: [
        { id: 'rev_004_r1', author: 'Tesla Team', avatar: 'https://i.pravatar.cc/150?img=68', text: 'We\'re continuously improving app connectivity. Try updating to the latest version!', time: '1 month ago' },
      ],
    },
    {
      id: 'rev_005',
      author: 'Robert Kim',
      avatar: 'https://i.pravatar.cc/150?img=52',
      rating: 5,
      time: '2 months ago',
      title: 'Best car I\'ve ever owned',
      text: 'Coming from a BMW M5, this is a completely different league. The instant torque is addictive and I haven\'t been to a gas station in 4 months. Supercharging is seamless.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_006',
      author: 'Aisha Johnson',
      avatar: 'https://i.pravatar.cc/150?img=44',
      rating: 5,
      time: '3 months ago',
      title: 'Family road trip ready',
      text: 'Drove from LA to Denver with two kids. Superchargers were perfectly spaced and the kids watched movies on the display. 1,000 miles and it felt effortless.',
      verified: true,
      replies: [
        { id: 'rev_006_r1', author: 'Tom Henderson', avatar: 'https://i.pravatar.cc/150?img=13', text: 'Planning a similar trip. How was the range through the mountains?', time: '2 months ago' },
        { id: 'rev_006_r2', author: 'Aisha Johnson', avatar: 'https://i.pravatar.cc/150?img=44', text: 'Lost about 15% going over Vail Pass but the nav routed us to a supercharger perfectly.', time: '2 months ago' },
      ],
    },
    {
      id: 'rev_007',
      author: 'Liam O\'Brien',
      avatar: 'https://i.pravatar.cc/150?img=15',
      rating: 4,
      time: '3 months ago',
      title: 'Phenomenal but pricey',
      text: 'The performance is worth every penny if you can afford it. FSD is impressive in beta but still needs supervision. Deducted a star for the price of the FSD package.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_008',
      author: 'Nadia Volkov',
      avatar: 'https://i.pravatar.cc/150?img=20',
      rating: 5,
      time: '4 months ago',
      title: 'Glass roof is gorgeous',
      text: 'The panoramic glass roof makes the cabin feel enormous. UV protection works well — even in Phoenix summer the cabin stays manageable with pre-conditioning.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_009',
      author: 'Carlos Mendes',
      avatar: 'https://i.pravatar.cc/150?img=53',
      rating: 5,
      time: '4 months ago',
      title: 'Sentry Mode saved my car',
      text: 'Someone keyed my car in a parking lot and Sentry Mode caught the whole thing on camera. Gave the footage to police and they caught the guy. Worth it alone.',
      verified: true,
      replies: [
        { id: 'rev_009_r1', author: 'Priya Sharma', avatar: 'https://i.pravatar.cc/150?img=45', text: 'Same thing happened to me! Sentry is a game changer for parking in the city.', time: '3 months ago' },
      ],
    },
    {
      id: 'rev_010',
      author: 'Hannah Park',
      avatar: 'https://i.pravatar.cc/150?img=49',
      rating: 4,
      time: '5 months ago',
      title: 'Service experience was great',
      text: 'Had a minor panel gap issue and mobile service came to my office and fixed it in 20 minutes. No trip to a service center needed. Impressive support.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_011',
      author: 'Ben Carter',
      avatar: 'https://i.pravatar.cc/150?img=14',
      rating: 5,
      time: '5 months ago',
      title: 'Gaming in the car is wild',
      text: 'Waiting for my wife at the store, I played Stardew Valley on the center screen with a controller. The car is genuinely a gaming platform. My kids love it on road trips.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_012',
      author: 'Mei Lin',
      avatar: 'https://i.pravatar.cc/150?img=41',
      rating: 5,
      time: '6 months ago',
      title: 'Charging at home changed my life',
      text: 'I never thought about how much time I spent at gas stations until I stopped going. Plug in at night, full tank every morning. The convenience is unbeatable.',
      verified: true,
      replies: [
        { id: 'rev_012_r1', author: 'Diego Fernández', avatar: 'https://i.pravatar.cc/150?img=54', text: 'This is the thing non-EV owners don\'t get. Home charging is the killer feature.', time: '5 months ago' },
      ],
    },
    {
      id: 'rev_013',
      author: 'Olu Adesanya',
      avatar: 'https://i.pravatar.cc/150?img=43',
      rating: 4,
      time: '6 months ago',
      title: 'FSD is improving fast',
      text: 'I\'ve had FSD for a year and the progress is remarkable. It handles my daily commute with zero interventions now. Still not fully autonomous but getting closer every update.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_014',
      author: 'Greta Lindqvist',
      avatar: 'https://i.pravatar.cc/150?img=31',
      rating: 5,
      time: '7 months ago',
      title: 'Scandinavian winter tested',
      text: 'Drove through a Norwegian winter with -20°C temperatures. Range dropped about 30% but heat pump made a huge difference. Heated seats and steering wheel are lifesavers.',
      verified: true,
      replies: [
        { id: 'rev_014_r1', author: 'Yuki Tanaka', avatar: 'https://i.pravatar.cc/150?img=48', text: 'Similar experience in Hokkaido. The heat pump is a massive improvement over older models.', time: '6 months ago' },
      ],
    },
    {
      id: 'rev_015',
      author: 'Andre Costa',
      avatar: 'https://i.pravatar.cc/150?img=52',
      rating: 5,
      time: '8 months ago',
      title: 'Traded my Porsche for this',
      text: 'I was skeptical about switching from a Panamera to an EV. After a week I knew I\'d never go back. The Plaid is faster, quieter, more spacious, and costs less to run.',
      verified: true,
      replies: [],
    },
    {
      id: 'rev_016',
      author: 'Clara Moreau',
      avatar: 'https://i.pravatar.cc/150?img=24',
      rating: 4,
      time: '9 months ago',
      title: 'Wish it had CarPlay',
      text: 'The native infotainment is good but I really miss CarPlay for Spotify and podcasts. The built-in music app is fine but not as polished as Apple\'s ecosystem.',
      verified: true,
      replies: [
        { id: 'rev_016_r1', author: 'Ravi Kapoor', avatar: 'https://i.pravatar.cc/150?img=11', text: 'Agreed. Bluetooth audio works well enough but CarPlay would be the cherry on top.', time: '8 months ago' },
      ],
    },
  ],

  // ---------------------------------------------------------------------------
  // 6. CART ITEMS
  // ---------------------------------------------------------------------------
  'tesla.cart.items': [
    {
      id: 'cart_model_s',
      modelId: 'model_s',
      name: 'Model S Plaid',
      paint: 'Pearl White Multi-Coat',
      paintPrice: 0,
      wheels: '19" Tempest Wheels',
      wheelsPrice: 0,
      interior: 'All Black',
      interiorPrice: 0,
      autopilot: 'Full Self-Driving Capability',
      autopilotPrice: 15000,
      basePrice: 89990,
      destinationFee: 1640,
      estSavings: -5200,
      subtotal: 108430,
      image: 'https://picsum.photos/seed/modelscart/600/400',
    },
  ],

  // ---------------------------------------------------------------------------
  // 7. SHOWROOM LOCATIONS (10+)
  // ---------------------------------------------------------------------------
  'tesla.locations': [
    { id: 'loc_palo_alto', name: 'Palo Alto', address: '4180 El Camino Real, Palo Alto, CA 94306', phone: '(650) 681-5100', hours: '10am-7pm', lat: 37.4268, lng: -122.1423 },
    { id: 'loc_la', name: 'Los Angeles', address: '8535 Beverly Blvd, Los Angeles, CA 90048', phone: '(323) 634-8300', hours: '10am-8pm', lat: 34.0762, lng: -118.3793 },
    { id: 'loc_brooklyn', name: 'Brooklyn', address: '160 Imlay Street, Brooklyn, NY 11231', phone: '(718) 858-2900', hours: '10am-7pm', lat: 40.6745, lng: -74.0086 },
    { id: 'loc_chicago', name: 'Chicago', address: '1544 N Clybourn Ave, Chicago, IL 60610', phone: '(312) 266-5800', hours: '10am-7pm', lat: 41.9103, lng: -87.6547 },
    { id: 'loc_miami', name: 'Miami', address: '8300 NE 2nd Ave, Miami, FL 33138', phone: '(305) 751-8000', hours: '10am-7pm', lat: 25.8132, lng: -80.1918 },
    { id: 'loc_seattle', name: 'Seattle', address: '3601 4th Ave S, Seattle, WA 98134', phone: '(206) 504-3400', hours: '10am-7pm', lat: 47.5818, lng: -122.3376 },
    { id: 'loc_austin', name: 'Austin', address: '12720 Shops Pkwy, Cedar Park, TX 78613', phone: '(512) 528-8100', hours: '10am-7pm', lat: 30.5290, lng: -97.8156 },
    { id: 'loc_denver', name: 'Denver', address: '9201 E Hampden Ave, Denver, CO 80231', phone: '(303) 752-4400', hours: '10am-7pm', lat: 39.6517, lng: -104.8953 },
    { id: 'loc_boston', name: 'Boston', address: '75 2nd Ave, Needham, MA 02494', phone: '(781) 559-4800', hours: '10am-7pm', lat: 42.2823, lng: -71.2373 },
    { id: 'loc_atlanta', name: 'Atlanta', address: '5955 Peachtree Pkwy, Norcross, GA 30092', phone: '(770) 242-4400', hours: '10am-7pm', lat: 33.9583, lng: -84.2273 },
    { id: 'loc_phoenix', name: 'Phoenix', address: '6420 E Mayo Blvd, Phoenix, AZ 85054', phone: '(480) 585-6400', hours: '10am-7pm', lat: 33.7022, lng: -111.9279 },
    { id: 'loc_san_diego', name: 'San Diego', address: '4650 La Jolla Village Dr, San Diego, CA 92122', phone: '(858) 450-5500', hours: '10am-7pm', lat: 32.8718, lng: -117.2143 },
  ],

  // ---------------------------------------------------------------------------
  // 8. SUPERCHARGER STATIONS (10+)
  // ---------------------------------------------------------------------------
  'tesla.charging': [
    { id: 'sc_hawthorne', location: 'Hawthorne, CA', address: '12520 Hawthorne Blvd', stalls: 12, power: '250 kW', status: 'Available' },
    { id: 'sc_fremont', location: 'Fremont, CA', address: '45500 Fremont Blvd', stalls: 20, power: '250 kW', status: 'Available' },
    { id: 'sc_vegas', location: 'Las Vegas, NV', address: '6135 Las Vegas Blvd S', stalls: 16, power: '250 kW', status: 'Busy' },
    { id: 'sc_denver', location: 'Denver, CO', address: '9201 E Hampden Ave', stalls: 8, power: '250 kW', status: 'Available' },
    { id: 'sc_flagstaff', location: 'Flagstaff, AZ', address: '1851 S Woodlands Village Blvd', stalls: 8, power: '250 kW', status: 'Available' },
    { id: 'sc_abq', location: 'Albuquerque, NM', address: '1500 Golf Course Rd', stalls: 6, power: '250 kW', status: 'Available' },
    { id: 'sc_amarillo', location: 'Amarillo, TX', address: '3300 E Interstate 40', stalls: 6, power: '250 kW', status: 'Available' },
    { id: 'sc_okc', location: 'Oklahoma City, OK', address: '10101 N Pennsylvania Ave', stalls: 8, power: '250 kW', status: 'Busy' },
    { id: 'sc_dallas', location: 'Dallas, TX', address: '8550 Stemmons Fwy', stalls: 12, power: '250 kW', status: 'Available' },
    { id: 'sc_memphis', location: 'Memphis, TN', address: '5900 Poplar Ave', stalls: 6, power: '250 kW', status: 'Available' },
    { id: 'sc_nashville', location: 'Nashville, TN', address: '2416 Elliston Pl', stalls: 8, power: '250 kW', status: 'Available' },
    { id: 'sc_knoxville', location: 'Knoxville, TN', address: '8701 Kingston Pike', stalls: 6, power: '250 kW', status: 'Available' },
  ],
};
