import { PINTEREST_WELCOME_PAGE } from './welcome';
import { PINTEREST_BOARD_PAGE } from './board';
import { PINTEREST_PIN_PAGE } from './pin';

export { PINTEREST_WELCOME_PAGE, PINTEREST_BOARD_PAGE, PINTEREST_PIN_PAGE };

export const PINTEREST_PAGES = [
  PINTEREST_WELCOME_PAGE,
  PINTEREST_BOARD_PAGE,
  PINTEREST_PIN_PAGE,
];
