import { APP_STORE_ABOUT_PAGE } from './about';
import { APP_STORE_WELCOME_PAGE } from './welcome';
import { APP_STORE_CATEGORY_PAGE } from './category';
import { APP_STORE_APP_DETAIL_PAGE } from './app';

export { APP_STORE_ABOUT_PAGE, APP_STORE_WELCOME_PAGE, APP_STORE_CATEGORY_PAGE, APP_STORE_APP_DETAIL_PAGE };

export const APP_STORE_PAGES = [
  APP_STORE_WELCOME_PAGE,
  APP_STORE_CATEGORY_PAGE,
  APP_STORE_APP_DETAIL_PAGE,
  APP_STORE_ABOUT_PAGE,
];
