/* ---------- X.com (Twitter) page data (pure data, no functions) ---------- */

export const X_DATA: Record<string, any> = {
  /* 1. Categories / tabs */
  'x.categories': [
    { id: 'foryou', name: 'For you' },
    { id: 'following', name: 'Following' },
    { id: 'news', name: 'News' },
    { id: 'sports', name: 'Sports' },
    { id: 'entertainment', name: 'Entertainment' },
    { id: 'technology', name: 'Technology' },
  ],

  /* 2. Feed tweets */
  'x.feed.tweets': [
    {
      id: 't-1001',
      author: 'Sarah Chen',
      handle: '@sarahchen',
      avatar: 'https://i.pravatar.cc/150?img=1',
      text: 'Just shipped our new design system at work. Took 6 months of iteration but the consistency gains are already paying off. Design tokens > hardcoded values every time.',
      time: '2h',
      likes: 1284,
      reposts: 142,
      replies: 89,
      views: 18400,
      verified: true,
      media: null,
    },
    {
      id: 't-1002',
      author: 'Marcus Williams',
      handle: '@marcusw_dev',
      avatar: 'https://i.pravatar.cc/150?img=12',
      text: 'TypeScript 5.4 is a game changer for our codebase. The new type inference patterns cut our generic boilerplate in half. Upgrade was smooth too.',
      time: '4h',
      likes: 892,
      reposts: 234,
      replies: 56,
      views: 12700,
      verified: false,
      media: 'image',
    },
    {
      id: 't-1003',
      author: 'The Verge',
      handle: '@verge',
      avatar: 'https://i.pravatar.cc/150?img=33',
      text: 'Apple announces new M4 Ultra chip with 32-core CPU and 80-core GPU. Claims 2x performance over M2 Ultra while using 40% less power. Shipping in Mac Studio next month.',
      time: '5h',
      likes: 4521,
      reposts: 1820,
      replies: 412,
      views: 892000,
      verified: true,
      media: 'image',
    },
    {
      id: 't-1004',
      author: 'Priya Sharma',
      handle: '@priyasharma',
      avatar: 'https://i.pravatar.cc/150?img=5',
      text: 'Reminder: accessibility is not a feature, it is a baseline. If your component library does not pass WCAG 2.2 AA out of the box, it is not production ready.',
      time: '6h',
      likes: 2103,
      reposts: 689,
      replies: 134,
      views: 42100,
      verified: true,
      media: null,
    },
    {
      id: 't-1005',
      author: 'James Okafor',
      handle: '@jokafor',
      avatar: 'https://i.pravatar.cc/150?img=15',
      text: 'Spent the weekend rebuilding my personal site with Astro. The islands architecture is honestly perfect for content-heavy sites. Lighthouse score went from 67 to 100.',
      time: '8h',
      likes: 567,
      reposts: 78,
      replies: 42,
      views: 9800,
      verified: false,
      media: null,
    },
    {
      id: 't-1006',
      author: 'ESPN',
      handle: '@espn',
      avatar: 'https://i.pravatar.cc/150?img=51',
      text: 'BREAKING: Lakers acquire All-Star forward in blockbuster trade deadline deal. Three first-round picks heading the other way. Full details on SportsCenter at 6 ET.',
      time: '9h',
      likes: 38900,
      reposts: 12400,
      replies: 3200,
      views: 2100000,
      verified: true,
      media: null,
    },
    {
      id: 't-1007',
      author: 'Elena Rodriguez',
      handle: '@elenarod',
      avatar: 'https://i.pravatar.cc/150?img=9',
      text: 'Hot take: most teams do not need a microservices architecture. A well-structured monolith with clear module boundaries will outperform your distributed system at a fraction of the operational cost.',
      time: '10h',
      likes: 3421,
      reposts: 890,
      replies: 287,
      views: 67000,
      verified: true,
      media: null,
    },
    {
      id: 't-1008',
      author: 'TechCrunch',
      handle: '@techcrunch',
      avatar: 'https://i.pravatar.cc/150?img=28',
      text: 'Startup raises $40M Series B to build AI-powered code review tool. Early adopters report catching 3x more bugs before production. Investors include Andreessen Horowitz and Sequoia.',
      time: '11h',
      likes: 1890,
      reposts: 456,
      replies: 198,
      views: 54000,
      verified: true,
      media: 'image',
    },
    {
      id: 't-1009',
      author: 'David Kim',
      handle: '@davidkim_ui',
      avatar: 'https://i.pravatar.cc/150?img=14',
      text: 'The best UX advice I ever got: design for the user who is having the worst day of their life. If your interface works for them, it works for everyone.',
      time: '12h',
      likes: 8900,
      reposts: 2100,
      replies: 234,
      views: 156000,
      verified: false,
      media: null,
    },
    {
      id: 't-1010',
      author: 'NASA',
      handle: '@nasa',
      avatar: 'https://i.pravatar.cc/150?img=68',
      text: 'New images from the James Webb Space Telescope reveal a galaxy cluster 13 billion light-years away. The light we see today started its journey when the universe was just 700 million years old.',
      time: '14h',
      likes: 124000,
      reposts: 34000,
      replies: 5600,
      views: 8900000,
      verified: true,
      media: 'image',
    },
    {
      id: 't-1011',
      author: 'Aisha Bello',
      handle: '@aishabello',
      avatar: 'https://i.pravatar.cc/150?img=20',
      text: 'Been using Bun for 3 months in production. Cold starts are 4x faster than Node and the built-in test runner replaced Jest entirely. No regrets so far.',
      time: '16h',
      likes: 1456,
      reposts: 312,
      replies: 178,
      views: 28900,
      verified: false,
      media: null,
    },
    {
      id: 't-1012',
      author: 'Netflix',
      handle: '@netflix',
      avatar: 'https://i.pravatar.cc/150?img=44',
      text: 'The new season drops this Friday. We have been waiting 18 months for this one and trust us, it was worth every minute. No spoilers in the replies please.',
      time: '18h',
      likes: 67000,
      reposts: 12000,
      replies: 8900,
      views: 3400000,
      verified: true,
      media: 'video',
    },
    {
      id: 't-1013',
      author: 'Liam Murphy',
      handle: '@liammurphy',
      avatar: 'https://i.pravatar.cc/150?img=17',
      text: 'PSA: your error states matter as much as your happy path. Spend the same effort designing empty states, loading skeletons, and error boundaries. Users remember when things break gracefully.',
      time: '20h',
      likes: 2340,
      reposts: 567,
      replies: 89,
      views: 38700,
      verified: false,
      media: null,
    },
    {
      id: 't-1014',
      author: 'Reuters',
      handle: '@reuters',
      avatar: 'https://i.pravatar.cc/150?img=58',
      text: 'Global markets rally as central banks signal pause on interest rate hikes. Tech stocks lead gains with Nasdaq up 2.8 percent. Analysts cautious about sustained recovery.',
      time: '22h',
      likes: 5600,
      reposts: 1900,
      replies: 445,
      views: 234000,
      verified: true,
      media: null,
    },
    {
      id: 't-1015',
      author: 'Sophie Laurent',
      handle: '@sophielaur',
      avatar: 'https://i.pravatar.cc/150?img=23',
      text: 'After 8 years of Vim I finally tried Helix and I am not going back. Built-in multi-cursor, no plugin hell, and the selection-first model just clicks. Give it a weekend.',
      time: '1d',
      likes: 987,
      reposts: 234,
      replies: 156,
      views: 18900,
      verified: false,
      media: null,
    },
  ],

  /* 3. Profile info */
  'x.profile.info': {
    name: 'Sarah Chen',
    handle: '@sarahchen',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Senior Product Designer @ Stripe. Writing about design systems, accessibility, and the craft of UI. Views are my own.',
    following: 842,
    followers: 24800,
    joinedDate: 'March 2014',
    verified: true,
  },

  /* 4. Profile tweets */
  'x.profile.tweets': [
    {
      id: 'p-2001',
      text: 'Just shipped our new design system at work. Took 6 months of iteration but the consistency gains are already paying off. Design tokens > hardcoded values every time.',
      time: '2h',
      likes: 1284,
      reposts: 142,
      replies: 89,
      views: 18400,
    },
    {
      id: 'p-2002',
      text: 'Thread on how we structure our Figma library for a team of 40 designers. The key is single-source components with variant properties, not duplicate frames.',
      time: '1d',
      likes: 2100,
      reposts: 445,
      replies: 67,
      views: 34000,
    },
    {
      id: 'p-2003',
      text: 'If your design tokens do not map 1:1 to your code tokens, you do not have a design system. You have two systems that will drift apart within a quarter.',
      time: '2d',
      likes: 3400,
      reposts: 890,
      replies: 134,
      views: 56000,
    },
    {
      id: 'p-2004',
      text: 'Hiring a senior designer to join the design systems team. Remote-friendly, competitive comp, and you get to work on tooling used by 2000+ engineers. DM if interested.',
      time: '3d',
      likes: 567,
      reposts: 1200,
      replies: 89,
      views: 89000,
    },
    {
      id: 'p-2005',
      text: 'Reminder that color contrast is not optional. 4.5:1 for normal text, 3:1 for large. Test with real users, not just automated tools. Both have blind spots.',
      time: '4d',
      likes: 1890,
      reposts: 567,
      replies: 45,
      views: 42000,
    },
    {
      id: 'p-2006',
      text: 'New blog post is live: building accessible modal dialogs from scratch. Covers focus trapping, scroll lock, and keyboard dismissal patterns that actually work.',
      time: '5d',
      likes: 2340,
      reposts: 678,
      replies: 92,
      views: 61000,
    },
    {
      id: 'p-2007',
      text: 'Unpopular opinion: skeleton screens are overused. For interactions under 200ms, a subtle opacity transition is better than a flashing placeholder.',
      time: '6d',
      likes: 1456,
      reposts: 234,
      replies: 187,
      views: 28000,
    },
    {
      id: 'p-2008',
      text: 'Spoke at Config last week about scaling design systems across product orgs. Slides and recording are up on my site. Thanks to everyone who came to the talk.',
      time: '1w',
      likes: 3200,
      reposts: 890,
      replies: 156,
      views: 78000,
    },
    {
      id: 'p-2009',
      text: 'The best feedback I got this year: your design system is not done when you ship it. It is done when a new designer can build a screen without asking anyone a question.',
      time: '1w',
      likes: 5600,
      reposts: 1800,
      replies: 234,
      views: 142000,
    },
    {
      id: 'p-2010',
      text: 'Working on a new talk about the economics of design systems. Spoiler: the ROI is not in designer time saved, it is in engineer time saved during implementation.',
      time: '1w',
      likes: 1234,
      reposts: 345,
      replies: 78,
      views: 31000,
    },
    {
      id: 'p-2011',
      text: 'Hot take: most design system documentation sites are too focused on API reference and not enough on when to use what. Decision trees > property tables.',
      time: '2w',
      likes: 2890,
      reposts: 712,
      replies: 198,
      views: 54000,
    },
    {
      id: 'p-2012',
      text: 'Year in review: shipped 47 components, deprecated 12, wrote 23 docs pages, ran 14 office hours sessions. Design systems are a marathon, not a sprint.',
      time: '2w',
      likes: 4100,
      reposts: 1100,
      replies: 287,
      views: 96000,
    },
  ],

  /* 5. Tweet detail */
  'x.tweet.detail': {
    id: 't-1001',
    author: 'Sarah Chen',
    handle: '@sarahchen',
    avatar: 'https://i.pravatar.cc/150?img=1',
    text: 'Just shipped our new design system at work. Took 6 months of iteration but the consistency gains are already paying off. Design tokens > hardcoded values every time.',
    time: '2h',
    likes: 1284,
    reposts: 142,
    replies: 89,
    views: 18400,
    verified: true,
  },

  /* 6. Tweet replies with nested replies */
  'x.tweet.replies': [
    {
      id: 'r-3001',
      author: 'Marcus Williams',
      handle: '@marcusw_dev',
      avatar: 'https://i.pravatar.cc/150?img=12',
      text: 'This resonates so much. We just went through the same migration and the token pipeline alone saved us weeks of refactoring. What tool did you use for token transforms?',
      time: '1h',
      likes: 142,
      replies: [
        {
          id: 'r-3001a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'We use Style Dictionary for the transform layer and pipe the output directly into our CSS variables build. Works across web and React Native.',
          time: '45m',
          likes: 89,
        },
        {
          id: 'r-3001b',
          author: 'Marcus Williams',
          handle: '@marcusw_dev',
          avatar: 'https://i.pravatar.cc/150?img=12',
          text: 'Perfect, that is exactly the stack I was considering. Thanks for confirming it scales to a team your size.',
          time: '30m',
          likes: 34,
        },
      ],
    },
    {
      id: 'r-3002',
      author: 'Priya Sharma',
      handle: '@priyasharma',
      avatar: 'https://i.pravatar.cc/150?img=5',
      text: 'The 6 months part is the real lesson here. So many teams give up on design systems after week 3 because the ROI is not immediate. Patience is the feature.',
      time: '1h',
      likes: 287,
      replies: [
        {
          id: 'r-3002a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'Completely agree. Month 3 was the hardest, we had tokens but no components yet and leadership was asking for metrics. Glad we pushed through.',
          time: '50m',
          likes: 156,
        },
      ],
    },
    {
      id: 'r-3003',
      author: 'David Kim',
      handle: '@davidkim_ui',
      avatar: 'https://i.pravatar.cc/150?img=14',
      text: 'Curious how you handle semantic vs primitive tokens. We have been debating whether to expose raw color tokens to product teams or force everything through semantic aliases.',
      time: '2h',
      likes: 98,
      replies: [
        {
          id: 'r-3003a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'We lock down primitives entirely. Product teams only get semantic tokens like surface-primary and text-secondary. It makes theming trivial.',
          time: '1h',
          likes: 112,
        },
        {
          id: 'r-3003b',
          author: 'David Kim',
          handle: '@davidkim_ui',
          avatar: 'https://i.pravatar.cc/150?img=14',
          text: 'That is clean. We tried exposing both and immediately had teams using raw hex values in their CSS. Never again.',
          time: '55m',
          likes: 67,
        },
        {
          id: 'r-3003c',
          author: 'Elena Rodriguez',
          handle: '@elenarod',
          avatar: 'https://i.pravatar.cc/150?img=9',
          text: 'Same approach here. The indirection pays for itself the first time you rebrand without touching a single product file.',
          time: '40m',
          likes: 45,
        },
      ],
    },
    {
      id: 'r-3004',
      author: 'James Okafor',
      handle: '@jokafor',
      avatar: 'https://i.pravatar.cc/150?img=15',
      text: 'Congrats on the ship! What was the hardest component to get right? In my experience date pickers and data tables are always the time sinks.',
      time: '2h',
      likes: 56,
      replies: [
        {
          id: 'r-3004a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'Data tables, hands down. Virtualization, sticky headers, responsive collapse, and sorting states took 3 weeks alone. Date picker was week 2.',
          time: '1h',
          likes: 78,
        },
      ],
    },
    {
      id: 'r-3005',
      author: 'Aisha Bello',
      handle: '@aishabello',
      avatar: 'https://i.pravatar.cc/150?img=20',
      text: 'How did you measure success after launch? We are about to ship ours and leadership wants concrete numbers beyond component adoption.',
      time: '3h',
      likes: 73,
      replies: [],
    },
    {
      id: 'r-3006',
      author: 'Liam Murphy',
      handle: '@liammurphy',
      avatar: 'https://i.pravatar.cc/150?img=17',
      text: 'The hardcoded values point cannot be overstated. Before our system, we found 47 different shades of gray in production CSS. Forty-seven.',
      time: '3h',
      likes: 234,
      replies: [
        {
          id: 'r-3006a',
          author: 'Sophie Laurent',
          handle: '@sophielaur',
          avatar: 'https://i.pravatar.cc/150?img=23',
          text: 'We audited ours last quarter and found 112 unique box-shadow declarations. Now we have 4. The cleanup PR was glorious.',
          time: '2h',
          likes: 189,
        },
      ],
    },
    {
      id: 'r-3007',
      author: 'Elena Rodriguez',
      handle: '@elenarod',
      avatar: 'https://i.pravatar.cc/150?img=9',
      text: 'Design tokens are great until you have to support 3 brands, 2 density modes, and light/dark. Not saying do not do it, just budget for the complexity.',
      time: '4h',
      likes: 167,
      replies: [],
    },
    {
      id: 'r-3008',
      author: 'Sophie Laurent',
      handle: '@sophielaur',
      avatar: 'https://i.pravatar.cc/150?img=23',
      text: 'What was your governance model? We struggle with teams wanting to add one-off variants that then become permanent tech debt.',
      time: '4h',
      likes: 89,
      replies: [
        {
          id: 'r-3008a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'Every new variant requires a use-case doc and a sunset plan. If you cannot articulate when it stops being used, it does not get merged.',
          time: '3h',
          likes: 145,
        },
      ],
    },
    {
      id: 'r-3009',
      author: 'Marcus Williams',
      handle: '@marcusw_dev',
      avatar: 'https://i.pravatar.cc/150?img=12',
      text: 'Bookmarking this thread. We are 2 months into our migration and this is exactly the validation I needed to keep pushing.',
      time: '5h',
      likes: 45,
      replies: [],
    },
    {
      id: 'r-3010',
      author: 'Priya Sharma',
      handle: '@priyasharma',
      avatar: 'https://i.pravatar.cc/150?img=5',
      text: 'Would love to see a follow-up post on how you handled the migration from the old component library. That is where most teams stall.',
      time: '5h',
      likes: 112,
      replies: [
        {
          id: 'r-3010a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'Working on that post now. Short version: codemods for the mechanical changes, paired migration sessions for the tricky ones, and a hard sunset date.',
          time: '4h',
          likes: 178,
        },
        {
          id: 'r-3010b',
          author: 'Priya Sharma',
          handle: '@priyasharma',
          avatar: 'https://i.pravatar.cc/150?img=5',
          text: 'Codemods are the answer. We tried manual migration and it took a year. Second time around with codemods took 6 weeks.',
          time: '3h',
          likes: 92,
        },
      ],
    },
    {
      id: 'r-3011',
      author: 'David Kim',
      handle: '@davidkim_ui',
      avatar: 'https://i.pravatar.cc/150?img=14',
      text: 'The consistency gains are real but do not sleep on the documentation. A system nobody knows how to use is just shared code, not a system.',
      time: '6h',
      likes: 201,
      replies: [],
    },
    {
      id: 'r-3012',
      author: 'James Okafor',
      handle: '@jokafor',
      avatar: 'https://i.pravatar.cc/150?img=15',
      text: 'How did you handle the Figma to code sync? Manual handoff always drifts and plugins like Tokens Studio have their own learning curve.',
      time: '6h',
      likes: 67,
      replies: [
        {
          id: 'r-3012a',
          author: 'Sarah Chen',
          handle: '@sarahchen',
          avatar: 'https://i.pravatar.cc/150?img=1',
          text: 'Tokens Studio into a JSON file in our repo, then Style Dictionary transforms it. Designers push, CI builds, PR auto-opens. Fully automated.',
          time: '5h',
          likes: 134,
        },
      ],
    },
    {
      id: 'r-3013',
      author: 'Aisha Bello',
      handle: '@aishabello',
      avatar: 'https://i.pravatar.cc/150?img=20',
      text: 'Six months sounds fast honestly. Our last attempt took 14 months and still did not ship. What kept your team moving?',
      time: '7h',
      likes: 54,
      replies: [],
    },
    {
      id: 'r-3014',
      author: 'Liam Murphy',
      handle: '@liammurphy',
      avatar: 'https://i.pravatar.cc/150?img=17',
      text: 'The best design systems feel boring in the best way. Predictable, consistent, invisible. That is the goal.',
      time: '8h',
      likes: 312,
      replies: [],
    },
    {
      id: 'r-3015',
      author: 'Elena Rodriguez',
      handle: '@elenarod',
      avatar: 'https://i.pravatar.cc/150?img=9',
      text: 'Shipping is just the start. The real work is adoption, governance, and evolution. Budget for maintenance like you would for any other infrastructure.',
      time: '9h',
      likes: 178,
      replies: [],
    },
  ],

  /* 7. Trends */
  'x.trends': [
    { id: 'tr-1', category: 'Technology · Trending', title: '#TypeScript5', posts: '128K posts', rank: 1 },
    { id: 'tr-2', category: 'Technology · Trending', title: 'Bun', posts: '45.2K posts', rank: 2 },
    { id: 'tr-3', category: 'Design · Trending', title: '#DesignTokens', posts: '23.1K posts', rank: 3 },
    { id: 'tr-4', category: 'News · Trending', title: 'Apple Event', posts: '892K posts', rank: 4 },
    { id: 'tr-5', category: 'Sports · Trending', title: 'NBA Trade Deadline', posts: '1.2M posts', rank: 5 },
    { id: 'tr-6', category: 'Technology · Trending', title: '#WebGPU', posts: '18.7K posts', rank: 6 },
    { id: 'tr-7', category: 'Entertainment · Trending', title: 'Stranger Things', posts: '567K posts', rank: 7 },
    { id: 'tr-8', category: 'Technology · Trending', title: 'React 19', posts: '234K posts', rank: 8 },
    { id: 'tr-9', category: 'Science · Trending', title: 'JWST Galaxy', posts: '145K posts', rank: 9 },
    { id: 'tr-10', category: 'Business · Trending', title: '#SeriesB', posts: '12.3K posts', rank: 10 },
    { id: 'tr-11', category: 'Technology · Trending', title: '#Accessibility', posts: '67.8K posts', rank: 11 },
    { id: 'tr-12', category: 'News · Trending', title: 'Federal Reserve', posts: '345K posts', rank: 12 },
  ],

  /* 8. Who to follow */
  'x.whoToFollow': [
    {
      id: 'w-1',
      name: 'Dan Abramov',
      handle: '@dan_abramov',
      avatar: 'https://i.pravatar.cc/150?img=60',
      verified: true,
      bio: 'Working on React. Co-author of Redux and Create React App.',
    },
    {
      id: 'w-2',
      name: 'Addy Osmani',
      handle: '@addyosmani',
      avatar: 'https://i.pravatar.cc/150?img=61',
      verified: true,
      bio: 'Engineering leader at Google Chrome. Performance, architecture, and web tooling.',
    },
    {
      id: 'w-3',
      name: 'Brad Frost',
      handle: '@brad_frost',
      avatar: 'https://i.pravatar.cc/150?img=62',
      verified: true,
      bio: 'Web designer, speaker, author of Atomic Design.',
    },
    {
      id: 'w-4',
      name: 'Una Kravets',
      handle: '@una',
      avatar: 'https://i.pravatar.cc/150?img=63',
      verified: true,
      bio: 'Developer advocate at Google. CSS, web platform, and design systems.',
    },
    {
      id: 'w-5',
      name: 'Ryan Florence',
      handle: '@ryanflorence',
      avatar: 'https://i.pravatar.cc/150?img=64',
      verified: true,
      bio: 'Co-creator of React Router and Remix. Building better web infrastructure.',
    },
    {
      id: 'w-6',
      name: 'Sara Soueidan',
      handle: '@sarasoueidan',
      avatar: 'https://i.pravatar.cc/150?img=65',
      verified: true,
      bio: 'Independent UI engineer. SVG, accessibility, and front-end architecture.',
    },
    {
      id: 'w-7',
      name: 'Josh Comeau',
      handle: '@joshwcomeau',
      avatar: 'https://i.pravatar.cc/150?img=66',
      verified: true,
      bio: 'Educator and blogger. Teaching React, CSS, and animation at joyofreact.com.',
    },
    {
      id: 'w-8',
      name: 'Lea Verou',
      handle: '@leaverou',
      avatar: 'https://i.pravatar.cc/150?img=67',
      verified: true,
      bio: 'Invited expert at W3C CSS Working Group. Open web standards advocate.',
    },
    {
      id: 'w-9',
      name: 'Kent Dodds',
      handle: '@kentcdodds',
      avatar: 'https://i.pravatar.cc/150?img=69',
      verified: true,
      bio: 'Open source educator. Creator of Testing Library and Epic React.',
    },
    {
      id: 'w-10',
      name: 'Cassidy Williams',
      handle: '@cassidoo',
      avatar: 'https://i.pravatar.cc/150?img=70',
      verified: true,
      bio: 'Developer advocate. Building in public and teaching web dev.',
    },
  ],

  /* 9. Notifications */
  'x.notifications': [
    {
      id: 'n-1',
      type: 'like',
      actor: 'Marcus Williams',
      handle: '@marcusw_dev',
      avatar: 'https://i.pravatar.cc/150?img=12',
      text: 'liked your post about design tokens and hardcoded values',
      time: '12m',
    },
    {
      id: 'n-2',
      type: 'repost',
      actor: 'Priya Sharma',
      handle: '@priyasharma',
      avatar: 'https://i.pravatar.cc/150?img=5',
      text: 'reposted your thread on Figma library structure',
      time: '34m',
    },
    {
      id: 'n-3',
      type: 'reply',
      actor: 'David Kim',
      handle: '@davidkim_ui',
      avatar: 'https://i.pravatar.cc/150?img=14',
      text: 'replied: Curious how you handle semantic vs primitive tokens...',
      time: '1h',
    },
    {
      id: 'n-4',
      type: 'follow',
      actor: 'Elena Rodriguez',
      handle: '@elenarod',
      avatar: 'https://i.pravatar.cc/150?img=9',
      text: 'followed you',
      time: '2h',
    },
    {
      id: 'n-5',
      type: 'like',
      actor: 'James Okafor',
      handle: '@jokafor',
      avatar: 'https://i.pravatar.cc/150?img=15',
      text: 'and 142 others liked your post about accessibility baselines',
      time: '3h',
    },
    {
      id: 'n-6',
      type: 'reply',
      actor: 'Aisha Bello',
      handle: '@aishabello',
      avatar: 'https://i.pravatar.cc/150?img=20',
      text: 'replied: How did you measure success after launch?',
      time: '5h',
    },
    {
      id: 'n-7',
      type: 'repost',
      actor: 'Sophie Laurent',
      handle: '@sophielaur',
      avatar: 'https://i.pravatar.cc/150?img=23',
      text: 'reposted your blog post about accessible modal dialogs',
      time: '8h',
    },
    {
      id: 'n-8',
      type: 'follow',
      actor: 'Liam Murphy',
      handle: '@liammurphy',
      avatar: 'https://i.pravatar.cc/150?img=17',
      text: 'followed you',
      time: '12h',
    },
    {
      id: 'n-9',
      type: 'like',
      actor: 'Josh Comeau',
      handle: '@joshwcomeau',
      avatar: 'https://i.pravatar.cc/150?img=66',
      text: 'liked your post about skeleton screens being overused',
      time: '1d',
    },
    {
      id: 'n-10',
      type: 'reply',
      actor: 'Una Kravets',
      handle: '@una',
      avatar: 'https://i.pravatar.cc/150?img=63',
      text: 'replied: Love the decision tree approach for docs. We are doing the same.',
      time: '1d',
    },
  ],

  /* 10. Messages / conversations */
  'x.messages': [
    {
      id: 'm-1',
      name: 'Marcus Williams',
      handle: '@marcusw_dev',
      avatar: 'https://i.pravatar.cc/150?img=12',
      lastMessage: 'That Style Dictionary setup sounds perfect. Can you share the config?',
      time: '5m',
      unread: 2,
    },
    {
      id: 'm-2',
      name: 'Priya Sharma',
      handle: '@priyasharma',
      avatar: 'https://i.pravatar.cc/150?img=5',
      lastMessage: 'Would love to chat about your Config talk. Coffee next week?',
      time: '1h',
      unread: 0,
    },
    {
      id: 'm-3',
      name: 'David Kim',
      handle: '@davidkim_ui',
      avatar: 'https://i.pravatar.cc/150?img=14',
      lastMessage: 'Sent you the semantic token mapping doc. Let me know what you think.',
      time: '3h',
      unread: 1,
    },
    {
      id: 'm-4',
      name: 'Elena Rodriguez',
      handle: '@elenarod',
      avatar: 'https://i.pravatar.cc/150?img=9',
      lastMessage: 'The multi-brand token matrix is finally working. Demo on Thursday?',
      time: '6h',
      unread: 0,
    },
    {
      id: 'm-5',
      name: 'James Okafor',
      handle: '@jokafor',
      avatar: 'https://i.pravatar.cc/150?img=15',
      lastMessage: 'Thanks for the Astro recommendation. Migration went smoothly.',
      time: '12h',
      unread: 0,
    },
    {
      id: 'm-6',
      name: 'Aisha Bello',
      handle: '@aishabello',
      avatar: 'https://i.pravatar.cc/150?img=20',
      lastMessage: 'Can you review the success metrics doc before our leadership review?',
      time: '1d',
      unread: 3,
    },
    {
      id: 'm-7',
      name: 'Sophie Laurent',
      handle: '@sophielaur',
      avatar: 'https://i.pravatar.cc/150?img=23',
      lastMessage: 'The box-shadow cleanup PR merged. Down from 112 to 4 declarations.',
      time: '2d',
      unread: 0,
    },
    {
      id: 'm-8',
      name: 'Liam Murphy',
      handle: '@liammurphy',
      avatar: 'https://i.pravatar.cc/150?img=17',
      lastMessage: 'Loved your error states thread. Sharing it with my team this sprint.',
      time: '3d',
      unread: 0,
    },
  ],
};
