import { YOUTUBE_WELCOME_PAGE } from './welcome';
import { YOUTUBE_FEED_PAGE } from './feed';
import { YOUTUBE_WATCH_PAGE } from './watch';
import { YOUTUBE_CHANNEL_PAGE } from './channel';

export { YOUTUBE_WELCOME_PAGE, YOUTUBE_FEED_PAGE, YOUTUBE_WATCH_PAGE, YOUTUBE_CHANNEL_PAGE };

export const YOUTUBE_PAGES = [
  YOUTUBE_WELCOME_PAGE,
  YOUTUBE_FEED_PAGE,
  YOUTUBE_WATCH_PAGE,
  YOUTUBE_CHANNEL_PAGE,
];
