"""Phient Ontologies Package — 1:1 Palantir Ontologies Module and P* Standard Classes."""

from __future__ import annotations

from .action import (
    ActionClient,
    ActionParameter,
    ActionType,
    ActionTypeClient,
    ActionTypeFullMetadata,
    PActionParameter,
    PActionType,
    PActionTypeFullMetadata,
)
from .attachment import Attachment, AttachmentClient, AttachmentProperty
from .cipher import CipherClient, CipherTextProperty
from .engine import (
    GLOBAL_ONTOLOGY,
    GLOBAL_TOPOS,
    OntologyEngine,
    POntologyEngine,
    PToposEngine,
    ToposEngine,
)
from .errors import (
    ActionExecutionError,
    LinkTypeNotFoundError,
    ObjectNotFoundError,
    OntologyError,
    ToposError,
)
from .geo import GeotemporalClient, GeotemporalSeriesProperty
from .interface import (
    InterfaceClient,
    OntologyInterface,
    OntologyInterfaceClient,
    POntologyInterface,
    POntologyInterfaceClient,
    ToposInterface,
    ToposInterfaceClient,
)
from .link import (
    LinkClient,
    LinkType,
    LinkedObjectClient,
    PLinkClient,
    PLinkType,
    PLinkedObjectClient,
)
from .media import MediaClient, MediaReferenceProperty
from .models import (
    OntologyObject,
    OntologyObjectSet,
    OntologyTransaction,
    POntologyObject,
    POntologyObjectSet,
    POntologyTransaction,
    PToposObject,
    PToposObjectSet,
    PToposTransaction,
    ToposObject,
    ToposObjectSet,
    ToposTransaction,
)
from .object import (
    ObjectClient,
    ObjectSetClient,
    ObjectType,
    ObjectTypeClient,
    OntologyObjectClient,
    OntologyObjectSetClient,
    PObjectClient,
    PObjectSetClient,
    PObjectType,
    PObjectTypeClient,
    PPropertyType,
    PropertyType,
    ToposObjectClient,
    ToposObjectSetClient,
)
from .ontology import (
    OntologyClient,
    POntology,
    POntologyClient,
    POntologyType,
    POntologyTypeClient,
    PTopoClient,
    TopoClient,
)
from .query import (
    PQueryType,
    QueryClient,
    QueryType,
    QueryTypeClient,
)
from .scenario import (
    OntologyScenario,
    OntologyScenarioClient,
    POntologyScenario,
    POntologyScenarioClient,
    ScenarioClient,
    ToposScenario,
    ToposScenarioClient,
)
from .timeseries import (
    TimeSeriesClient,
    TimeSeriesProperty,
    TimeSeriesPropertyV2,
    TimeSeriesValueBankProperty,
)
from .transaction import (
    OntologyTransactionClient,
    POntologyTransactionClient,
    ToposTransactionClient,
    TransactionClient,
)
from .value import (
    PValueType,
    ValueType,
    ValueTypeClient,
)
from ._client import (
    AsyncOntologyClient,
    AsyncOntologiesClient,
    AsyncToposClient,
    OntologyClient,
    OntologiesClient,
    PAsyncOntologyClient,
    PAsyncOntologiesClient,
    POntologyClient,
    POntologiesClient,
    ToposClient,
)

Ontology = OntologyClient

__all__ = [
    "Ontology",
    "POntology",
    "POntologyType",
    "OntologyClient",
    "AsyncOntologyClient",
    "POntologyClient",
    "PAsyncOntologyClient",
    "OntologiesClient",
    "AsyncOntologiesClient",
    "POntologiesClient",
    "PAsyncOntologiesClient",

    "ObjectType",
    "PObjectType",
    "PropertyType",
    "PPropertyType",
    "LinkType",
    "PLinkType",
    "ActionType",
    "PActionType",
    "ActionParameter",
    "PActionParameter",
    "ActionTypeFullMetadata",
    "PActionTypeFullMetadata",
    "OntologyEngine",
    "POntologyEngine",
    "GLOBAL_ONTOLOGY",
    "OntologyObject",
    "POntologyObject",
    "OntologyObjectSet",
    "POntologyObjectSet",
    "OntologyInterface",
    "POntologyInterface",
    "OntologyTransaction",
    "POntologyTransaction",
    "OntologyScenario",
    "POntologyScenario",
    "ValueType",
    "PValueType",
    "Attachment",
    "AttachmentProperty",
    "CipherTextProperty",
    "MediaReferenceProperty",
    "GeotemporalSeriesProperty",
    "TimeSeriesProperty",
    "TimeSeriesPropertyV2",
    "TimeSeriesValueBankProperty",
    "QueryType",
    "PQueryType",
    "ObjectClient",
    "PObjectClient",
    "ObjectSetClient",
    "PObjectSetClient",
    "ObjectTypeClient",
    "PObjectTypeClient",
    "OntologyObjectClient",
    "OntologyObjectSetClient",
    "ActionClient",
    "ActionTypeClient",
    "LinkClient",
    "PLinkClient",
    "LinkedObjectClient",
    "PLinkedObjectClient",
    "InterfaceClient",
    "OntologyInterfaceClient",
    "POntologyInterfaceClient",
    "TransactionClient",
    "OntologyTransactionClient",
    "POntologyTransactionClient",
    "ScenarioClient",
    "OntologyScenarioClient",
    "POntologyScenarioClient",
    "ValueTypeClient",
    "AttachmentClient",
    "CipherClient",
    "GeotemporalClient",
    "MediaClient",
    "TimeSeriesClient",
    "QueryClient",
    "QueryTypeClient",
    "OntologyClient",
    "POntologyClient",
    "POntologyTypeClient",
    "OntologyError",
    "ObjectNotFoundError",
    "LinkTypeNotFoundError",
    "ActionExecutionError",
    # Backward compatibility
    "ToposEngine",
    "PToposEngine",
    "GLOBAL_TOPOS",
    "ToposObject",
    "PToposObject",
    "ToposObjectSet",
    "PToposObjectSet",
    "ToposInterface",
    "PToposInterface",
    "ToposTransaction",
    "PToposTransaction",
    "ToposScenario",
    "ToposClient",
    "AsyncToposClient",
    "TopoClient",
    "PTopoClient",
    "ToposObjectClient",
    "ToposObjectSetClient",
    "ToposInterfaceClient",
    "ToposTransactionClient",
    "ToposScenarioClient",
    "ToposError",
]
