"""PhiGen Code Generation Engine — Synthesizes typed Python dataclasses from POntology ObjectTypes."""

from __future__ import annotations

from typing import Dict, List, Optional
from phiadk.agents.phigen.models import GeneratedClass
from phiadk.ontologies.engine import GLOBAL_ONTOLOGY as GLOBAL_TOPOS, POntologyEngine
from phiadk.ontologies.object import ObjectType



TYPE_MAPPING = {
    "string": "str",
    "integer": "int",
    "float": "float",
    "boolean": "bool",
    "timestamp": "str",
    "vector": "List[float]",
    "dict": "Dict[str, Any]",
}


class CodeGenerator:
    """Generates typed Python classes for ObjectTypes."""

    def __init__(self, engine: Optional[POntologyEngine] = None) -> None:
        self._engine = engine or GLOBAL_TOPOS

    def generate_class(self, ot: ObjectType) -> GeneratedClass:
        class_name = ot.api_name
        props_typed: Dict[str, str] = {}

        lines = [
            f"@dataclass",
            f"class {class_name}:",
            f'    """Typed POntology 0-Simplex for {ot.display_name}."""',
            f"",
            f"    primary_key: str",
        ]

        for p_name, p_meta in ot.properties.items():
            py_type = TYPE_MAPPING.get(p_meta.data_type, "Any")
            props_typed[p_name] = py_type
            if p_meta.is_primary_key:
                continue
            lines.append(f"    {p_name}: Optional[{py_type}] = None")

        lines.extend([
            "",
            "    def to_dict(self) -> Dict[str, Any]:",
            "        return {",
            '            "primary_key": self.primary_key,',
        ])
        for p_name in ot.properties.keys():
            if not ot.properties[p_name].is_primary_key:
                lines.append(f'            "{p_name}": self.{p_name},')
        lines.extend([
            "        }",
            "",
            "    @classmethod",
            f'    def from_topos_object(cls, obj) -> "{class_name}":',
            f"        return cls(",
            "            primary_key=obj.primary_key,",
        ])
        for p_name in ot.properties.keys():
            if not ot.properties[p_name].is_primary_key:
                lines.append(f"            {p_name}=obj.properties.get('{p_name}'),")
        lines.append("        )")

        code_str = "\n".join(lines)
        return GeneratedClass(
            class_name=class_name,
            object_type=ot.api_name,
            primary_key=ot.primary_key,
            properties=props_typed,
            code_str=code_str,
        )

    def generate_all_types(self) -> Dict[str, GeneratedClass]:
        return {
            name: self.generate_class(ot)
            for name, ot in self._engine.object_types.items()
        }

    def render_module_code(self) -> str:
        classes = self.generate_all_types()
        header = [
            '"""Auto-Generated Strongly-Typed POntology Object Classes.',
            "",
            "Generated by PhiGen toolchain. Do not edit manually.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass, field",
            "from typing import Any, Dict, List, Optional",
            "",
            "",
        ]
        body = "\n\n\n".join(c.code_str for c in classes.values())
        return "\n".join(header) + body + "\n"
