import { Object3DMeta } from './types';

export const OBJECT_3D_CATALOG: Object3DMeta[] = [
  {
    id: 'torus_manifold',
    name: 'Torus Manifold (T²)',
    category: 'Topological',
    formula: '(R + r cos θ) e^{i φ}',
    description: 'Multi-frequency continuous phase manifold with winding harmonics.',
  },
  {
    id: 'riemann_sphere',
    name: 'Riemann Hypersphere (S²)',
    category: 'Quantum',
    formula: 'z = tan(θ/2) e^{i φ}',
    description: 'Conformal stereographic sphere with Fibonacci phasor nodes.',
  },
  {
    id: 'klein_bottle',
    name: 'Klein Bottle Immersion',
    category: 'Topological',
    formula: '4D non-orientable immersion',
    description: 'Continuous self-intersecting non-orientable topological phase surface.',
  },
  {
    id: 'order_parameter_wheel',
    name: 'Kuramoto Order Sphere',
    category: 'Dynamical',
    formula: 'R e^{i ψ} = (1/N) ∑ e^{i θ_j}',
    description: '3D synchronization order parameter centroid with dipole oscillators.',
  },
  {
    id: 'hypercube_lattice',
    name: '16-Layer Hypercube',
    category: 'Cognitive',
    formula: '{0,1}⁴ Tesseract Lattice',
    description: '16-layer episodic memory hierarchy projected into 3D isometric space.',
  },
  {
    id: 'lorentz_attractor',
    name: 'Lorentz Chaos Attractor',
    category: 'Dynamical',
    formula: 'dx/dt = σ(y - x), dz/dt = xy - βz',
    description: 'Continuous dynamical trajectory flow in semantic state space.',
  },
  {
    id: 'calabi_yau',
    name: 'Calabi-Yau Subspace',
    category: 'Quantum',
    formula: 'z₁ⁿ + z₂ⁿ = 1 (Ricci-Flat)',
    description: 'Compactified 6D harmonic Calabi-Yau subspace cross-section.',
  },
  {
    id: 'mobius_strip',
    name: 'Möbius Phase Inversion',
    category: 'Topological',
    formula: 'v e^{i u/2} (π Anti-Phase)',
    description: 'Half-twist surface modeling 180° π-anti-phase destructive cancellation.',
  },
  {
    id: 'helical_syntax',
    name: 'Helical Syntax Spiral',
    category: 'Cognitive',
    formula: 'β_{ij} Asymmetric Lags',
    description: 'Double helix geometry with directed syntactic coupling base-pairs.',
  },
  {
    id: 'knowledge_graph',
    name: '3D Resonant Graph',
    category: 'Cognitive',
    formula: 'G = (V, E, W_{ij})',
    description: 'Topological force-directed semantic graph with harmonic pulse edges.',
  },
  {
    id: 'hyperbolic_pseudosphere',
    name: 'Pseudosphere (Beltrami)',
    category: 'Topological',
    formula: 'K = -1 (Hyperbolic Metric)',
    description: 'Constant negative curvature tractricoid for non-Euclidean embeddings.',
  },
  {
    id: 'wave_packet',
    name: 'Wave Packet Dispersion',
    category: 'Quantum',
    formula: 'Ψ(x, y, t) = e^{-r²/2σ²} e^{i(k·r - ωt)}',
    description: 'Continuous Gaussian wave packet propagating across cognitive field.',
  },
  {
    id: 'bloch_sphere',
    name: 'Quantum Bloch Sphere',
    category: 'Quantum',
    formula: '|ψ⟩ = cos(θ/2)|0⟩ + e^{iφ} sin(θ/2)|1⟩',
    description: 'Two-level semantic superposition state vector with precession orbit.',
  },
  {
    id: 'geodesic_icosahedron',
    name: 'Geodesic Icosahedron',
    category: 'Topological',
    formula: 'Golden Ratio Φ = (1+√5)/2',
    description: '8-chromatic sector harmonic cluster with subdivided geodesic facets.',
  },
  {
    id: 'hopf_fibration',
    name: 'Hopf Fibration Knots',
    category: 'Topological',
    formula: 'S³ → S² (p=3, q=5 Torus Knot)',
    description: 'Entangled fiber bundle circles wrapping around nested toroidal tubes.',
  },
  {
    id: 'synaptic_heatmap',
    name: 'Synaptic Coherence Mesh',
    category: 'Dynamical',
    formula: 'R(x, y) = |⟨e^{i θ(x,y)}⟩|',
    description: 'Dynamic 3D terrain heightmap reflecting real-time phase synchronization.',
  },
];
